version: 2
updates:
  - package-ecosystem: pnpm
    directory: "/"
    target-branch: main
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - maintenance

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci
