const assert = require('node:assert/strict');
const fs = require('node:fs');
const source = fs.readFileSync('src/agent-suggestions.ts', 'utf8');
assert.match(source, /requiresConfirmation: true/);
assert.match(source, /Object\.is\(item\[field\], after\)/);
assert.match(source, /summarizeSuggestionImpact/);
assert.match(source, /createSuggestionEnvelope/);
assert.match(source, /status: "pending"/);
assert.match(source, /if \(envelope.status !== "pending"\) return envelope/);
assert.match(source, /status === "confirmed" \? \{confirmedAt: now\}/);
assert.match(source, /error\.slice\(0, 160\)/);
assert.match(source, /ALLOWED_CHANGE_FIELDS/);
assert.match(source, /slice\(0, 50\)/);
assert.match(source, /formatSuggestionChange/);
assert.match(source, /renderSuggestionChanges/);
assert.match(source, /summarizeSuggestionChanges/);
assert.match(source, /suggestionStatusLabel/);
assert.match(source, /summarizeSuggestion\(envelope/);
assert.match(source, /canConfirmSuggestion/);
assert.match(source, /applyConfirmedSuggestion/);
assert.match(source, /normalizeSuggestionEnvelope/);
assert.match(source, /serializeSuggestionEnvelope/);
assert.match(source, /deserializeSuggestionEnvelope/);
assert.match(source, /normalizeSuggestionAudits/);
assert.match(source, /serializeSuggestionAudits/);
assert.match(source, /deserializeSuggestionAudits/);
assert.match(source, /appendSuggestionAudit/);
assert.match(source, /summarizeSuggestionAudits/);
assert.match(source, /AGENT_SUGGESTION_AUDIT_LIMIT/);
assert.match(source, /AGENT_SUGGESTION_AUDIT_VERSION/);
assert.match(source, /suggestionId: string/);
assert.match(source, /action: AgentSuggestionAuditAction/);
assert.match(source, /AGENT_SUGGESTION_MAX_TITLE_LENGTH/);
assert.match(source, /Date\.parse\(candidate\.createdAt\)/);
assert.match(source, /envelope\.status !== "confirmed"/);
assert.match(source, /conflicts: string\[\]/);
assert.match(source, /Object\.is\(next\[change\.field\], change\.before\)/);
assert.match(source, /createAnalysisMeta/);
assert.match(source, /appendAnalysisSnapshot/);
assert.match(source, /Math\.max\(1, Math\.min\(20/);
assert.match(source, /slice\(-safeLimit\)/);
assert.match(source, /loadAnalysisSnapshots/);
assert.match(source, /normalizeAnalysisSnapshots/);
assert.match(source, /return normalizeAnalysisSnapshots\(value\)/);
assert.match(source, /AGENT_ANALYSIS_MAX_TEXT_LENGTH/);
assert.match(source, /AGENT_ANALYSIS_MAX_SNAPSHOTS/);
assert.match(source, /Date\.parse\(candidate\.generatedAt\)/);
assert.match(source, /const seen = new Set<string>\(\)/);
assert.match(source, /saveAnalysisSnapshot/);
assert.match(source, /normalizeAnalysisSnapshots\(appendAnalysisSnapshot/);
assert.match(source, /AGENT_ANALYSIS_CACHE_KEY/);
assert.match(source, /source: "local" \| "agent"/);
assert.match(source, /escapeSuggestionHtml/);
assert.match(source, /diffAnalysisText/);
assert.match(source, /renderAnalysisDiff/);
assert.match(source, /summarizeAnalysisDiff/);
assert.match(source, /kind: "removed"/);
assert.match(source, /kind: "added"/);
const preview = fs.readFileSync('src/render/agent-preview.ts', 'utf8');
assert.match(preview, /renderAgentPreviewContent/);
assert.match(preview, /renderSuggestionChanges/);
assert.match(preview, /summarizeSuggestionImpact/);
const styles = fs.readFileSync('src/ui/components.scss', 'utf8');
assert.match(styles, /\.lc-agent-suggestion-changes/);
assert.match(styles, /\.lc-agent-suggestion-empty/);
assert.match(styles, /\.lc-agent-compare-diff/);
assert.match(styles, /max-height:220px/);
const i18n = fs.readFileSync("src/i18n.ts", "utf8");
assert.match(i18n, /"agent\.statusPending"/);
assert.match(i18n, /"agent\.impactSummary"/);
assert.match(i18n, /"agent\.changeSummary"/);
const diffPanel = fs.readFileSync('src/render/analysis-diff.ts', 'utf8');
assert.match(diffPanel, /renderAnalysisDiffPanel/);
assert.match(diffPanel, /新增/);
assert.match(diffPanel, /aria-label="[$][{]t[(]"agent[.]compareAria"[)][}]"/);
assert.match(i18n, /"agent.compareAria": "分析差异"/);
const previewText = fs.readFileSync('src/render/agent-preview.ts', 'utf8');
assert.match(previewText, /t\("agent\.previewReference"\)/);
assert.match(previewText, /t\("agent\.previewNoAutoApply"\)/);
console.log('Agent suggestion safety structure checks passed.');
require('./review-summary-refresh.test.cjs');
require('./suggestion-apply.test.cjs');
