const assert = require('node:assert/strict');
const fs = require('node:fs');
const source = fs.readFileSync('src/agent-suggestions.ts', 'utf8');
assert.match(source, /requiresConfirmation: true/);
assert.match(source, /Object\.is\(item\[field\], after\)/);
assert.match(source, /summarizeSuggestionImpact/);
assert.match(source, /createSuggestionEnvelope/);
assert.match(source, /status: "pending"/);
assert.match(source, /if \(envelope.status !== "pending"\) return envelope/);
assert.match(source, /status === "confirmed" \? \{confirmedAt: now\}/);
assert.match(source, /error\.slice\(0, 160\)/);
assert.match(source, /ALLOWED_CHANGE_FIELDS/);
assert.match(source, /slice\(0, 50\)/);
assert.match(source, /formatSuggestionChange/);
assert.match(source, /renderSuggestionChanges/);
assert.match(source, /escapeSuggestionHtml/);
const preview = fs.readFileSync('src/render/agent-preview.ts', 'utf8');
assert.match(preview, /renderAgentPreviewContent/);
assert.match(preview, /renderSuggestionChanges/);
console.log('Agent suggestion safety structure checks passed.');
