const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const source = fs.readFileSync(path.join(__dirname, "..", "src", "charts.ts"), "utf8");
assert.match(source, /export interface AnalyticsSnapshot/);
assert.match(source, /buildAnalyticsSnapshot\(store: CheckinStore/);
assert.match(source, /weekly: buildWeeklyCompletionTrend/);
assert.match(source, /monthly: buildMonthlyEventTrend/);
assert.match(source, /daily: buildDailyActivityTrend/);
assert.match(source, /yearly: buildYearlyEventTrend/);
assert.match(source, /export function buildYearlyEventTrend/);
assert.match(source, /cloneAnalyticsSnapshot/);
assert.match(source, /serializeAnalyticsSnapshot/);
assert.match(source, /parseAnalyticsSnapshot/);
assert.match(source, /value\.version !== 1/);
assert.match(source, /migrateAnalyticsEnvelope/);
assert.match(source, /migrated:/);
assert.match(source, /mergeAnalyticsSnapshots/);
assert.match(source, /if \(!current\)/);
assert.match(source, /Array\.isArray\(series\.points\)/);
assert.match(source, /\[\["weekly", value\.weekly\].*\["yearly", value\.yearly\]\]/s);
assert.match(source, /ANALYTICS_SERIES_LIMITS/);
assert.match(source, /series\.points\.length > ANALYTICS_SERIES_LIMITS\[name\]/);
assert.match(source, /Number\.isFinite\(point\.value\)/);
assert.match(source, /point\.label\.length > 64/);
assert.match(source, /point\.value < 0/);
assert.match(source, /value\[key\].*value\[key\] < 0/s);
assert.match(source, /buildWeeklyCompletionTrend\(store, 12, asOf\)/);
assert.match(source, /buildMonthlyEventTrend\(store, 6, asOf\)/);
assert.match(source, /buildDailyActivityTrend\(store, 30, asOf\)/);
assert.match(source, /buildYearlyEventTrend\(store, 5, asOf\)/);
assert.match(source, /const clampRange/);
assert.match(source, /Math\.min\(max, Math\.max\(1/);
assert.match(source, /Number\.isFinite\(value\) \? Math\.min/);
assert.match(source, /Math\.floor\(value\)/);
assert.match(source, /fallback/);
assert.match(source, /serializeAnalyticsSummary/);
assert.match(source, /parseAnalyticsSummary/);
assert.match(source, /isAnalyticsDate/);
assert.match(source, /\\d\{4\}-\\d\{2\}-\\d\{2\}/);
assert.match(source, /mergeAnalyticsSummaries/);
assert.match(source, /incoming\.asOf > current\.asOf/);
assert.match(source, /if \(!current \|\| incoming\.asOf > current\.asOf\)/);
assert.match(source, /value\[key\] !== \"number\"/);
assert.match(source, /return undefined;/);
assert.match(source, /catch \{\s*return undefined;/);
assert.match(source, /summarizeAnalyticsSnapshot/);
assert.match(source, /compareAnalyticsSnapshots/);
assert.match(source, /left\.asOf === right\.asOf/);
assert.match(source, /activeDays: snapshot\.daily\.points/);
assert.match(source, /yearlyCurrent: summarizeTrend\(snapshot\.yearly\)/);
assert.match(source, /AnalyticsSnapshotEnvelope/);
assert.match(source, /serializeAnalyticsEnvelope/);
assert.match(source, /parseAnalyticsEnvelope/);
assert.match(source, /value\.version !== 1/);
assert.match(source, /version: 1/);
console.log("Analytics snapshot contract checks passed.");
