const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const source = fs.readFileSync(path.join(__dirname, "..", "src", "charts.ts"), "utf8");
assert.match(source, /export interface AnalyticsSnapshot/);
assert.match(source, /buildAnalyticsSnapshot\(store: CheckinStore/);
assert.match(source, /weekly: buildWeeklyCompletionTrend/);
assert.match(source, /monthly: buildMonthlyEventTrend/);
assert.match(source, /daily: buildDailyActivityTrend/);
assert.match(source, /cloneAnalyticsSnapshot/);
assert.match(source, /serializeAnalyticsSnapshot/);
assert.match(source, /parseAnalyticsSnapshot/);
assert.match(source, /value\.version !== 1/);
assert.match(source, /migrateAnalyticsEnvelope/);
assert.match(source, /migrated:/);
assert.match(source, /mergeAnalyticsSnapshots/);
assert.match(source, /if \(!current\)/);
assert.match(source, /Array\.isArray\(series\.points\)/);
assert.match(source, /Number\.isFinite\(point\.value\)/);
assert.match(source, /catch \{\s*return undefined;/);
assert.match(source, /summarizeAnalyticsSnapshot/);
assert.match(source, /compareAnalyticsSnapshots/);
assert.match(source, /left\.asOf === right\.asOf/);
assert.match(source, /activeDays: snapshot\.daily\.points/);
assert.match(source, /AnalyticsSnapshotEnvelope/);
assert.match(source, /serializeAnalyticsEnvelope/);
assert.match(source, /parseAnalyticsEnvelope/);
assert.match(source, /value\.version !== 1/);
assert.match(source, /version: 1/);
console.log("Analytics snapshot contract checks passed.");
