const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const css = fs.readFileSync(path.join(root, "src", "ui", "components.scss"), "utf8");
const source = fs.readFileSync(path.join(root, "src", "index.ts"), "utf8");
for (const host of ["lc-checkin-dialog-host", "lc-checkin-tab-host", "lc-checkin-dock-host"]) assert.match(css, new RegExp(`\\.${host}`), `${host} must have a layout owner`);
for (const surface of ["today", "history", "occasions", "settings", "archived"]) assert.match(css, new RegExp(`lc-checkin--${surface}`), `${surface} surface must be styled`);
for (const width of ["320px", "340px", "360px", "380px", "719px"]) assert.match(css, new RegExp(`max-width: ${width.replace("px", "\\s*px")}`), `responsive tier ${width} must be declared`);
assert.match(css, /safe-area-inset-bottom/); assert.match(css, /safe-area-inset-top/);
assert.match(css, /:focus-visible/); assert.match(css, /overflow-x:\s*hidden/);
assert.match(source, /pageScrollTops/); assert.match(source, /pendingFocusItemId/);
console.log("Cross-surface 12.0 matrix checks passed.");
