const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const css = fs.readFileSync(path.join(root, "src", "ui", "components.scss"), "utf8");
const source = fs.readFileSync(path.join(root, "src", "index.ts"), "utf8");
for (const host of ["lc-checkin-dialog-host", "lc-checkin-tab-host", "lc-checkin-dock-host"]) assert.match(css, new RegExp(`\\.${host}`), `${host} must have a layout owner`);
for (const surface of ["today", "history", "occasions", "settings", "archived"]) assert.match(css, new RegExp(`lc-checkin--${surface}`), `${surface} surface must be styled`);
for (const width of ["320px", "340px", "360px", "380px", "719px"]) assert.match(css, new RegExp(`max-width: ${width.replace("px", "\\s*px")}`), `responsive tier ${width} must be declared`);
assert.match(css, /safe-area-inset-bottom/); assert.match(css, /safe-area-inset-top/);
assert.match(css, /\.lc-checkin__topnav[\s\S]*width: 100%/);
assert.match(css, /\.lc-checkin__topnav-tabs[\s\S]*overflow-x: auto/);
assert.match(css, /\.lc-checkin__topnav-actions \{ flex: 0 0 auto; min-width: 72px;/);
assert.match(css, /\.lc-checkin__topnav-tabs \{ display: flex; align-items: center; gap: 2px; min-width: 0; flex: 1 1 auto;/);
assert.match(css, /\.lc-checkin--review \.lc-checkin__summary-stats[\s\S]*repeat\(4, minmax\(0, 1fr\)\)/);
assert.match(css, /\.lc-checkin--review \.lc-checkin__review-fold-body[\s\S]*gap: 8px/);
assert.match(css, /\.lc-checkin--review \.lc-checkin__review-subnav \{ top: 58px;/);
assert.match(css, /review-subnav \{ top: 58px; gap: 4px;/);
assert.match(css, /review-subnav button \{ padding-inline: 10px; \}/);
assert.match(css, /\.lc-checkin--review \.lc-checkin__editor-header > :first-child[\s\S]*flex: 1 1 auto/);
assert.match(css, /:focus-visible/); assert.match(css, /overflow-x:\s*hidden/);
assert.match(css, /lc-checkin__analytics-badge/);
assert.match(css, /lc-checkin--review \.lc-checkin__summary-text[\s\S]*max-width: 1180px/);
assert.match(css, /lc-checkin--review \.lc-checkin__header-actions[\s\S]*max-width: 58%/);
assert.match(css, /minmax\(520px, 1\.05fr\)/);
assert.match(css, /minmax\(360px, \.95fr\)/);
assert.match(css, /\.lc-checkin__review-detail \{ min-width: 0; scrollbar-gutter: stable;/);
assert.match(css, /\.lc-checkin__review-calendar \{ max-width: 700px; width: 100%;/);
assert.match(css, /review-calendar \.lc-checkin__calendar-day \{ min-height: 40px; \}/);
assert.match(css, /review-detail \.lc-checkin__history-event \{ min-width: 0; overflow-wrap: anywhere; \}/);
assert.match(css, /review-detail \.lc-checkin__history-event-value,[\s\S]*flex: 0 0 auto; white-space: nowrap;/);
assert.match(css, /review \.lc-checkin__history-selected \{ padding: 10px 12px; \}/);
assert.match(css, /review \.lc-checkin__history-event \{ padding: 6px 0; \}/);
assert.match(css, /review-calendar:focus-within,[\s\S]*review-detail:focus-within \{ outline: 2px solid/);
assert.match(css, /forced-colors: active/);
assert.match(source, /pageScrollTops/); assert.match(source, /pendingFocusItemId/);
console.log("Cross-surface 12.0 matrix checks passed.");
