const assert = require("node:assert/strict");
const fs = require("node:fs");

const bridge = fs.readFileSync("src/dock-tomato.ts", "utf8");
const inbox = fs.readFileSync("src/features/docktomato-inbox.ts", "utf8");
const preferences = fs.readFileSync("src/view-preferences.ts", "utf8");
const settings = fs.readFileSync("src/render/settings.ts", "utf8");
const focus = fs.readFileSync("src/render/focus-adapter.ts", "utf8");
const today = fs.readFileSync("src/render/bind-today.ts", "utf8");
const i18n = fs.readFileSync("src/i18n.ts", "utf8");
const plugin = fs.readFileSync("src/index.ts", "utf8");

assert.match(bridge, /apiVersion !== 1/, "unknown Dock Tomato API versions must be rejected");
assert.match(bridge, /\["status", "start", "pause", "completion-event"\]/, "declared capabilities must be negotiated when present");
assert.match(bridge, /tomato:focus-api-availability-changed/, "either plugin load order must be supported");
assert.match(bridge, /tomato:focus-session-completed/, "durable completion events must be consumed");
assert.match(bridge, /externalRef: `docktomato:\$\{identity\}`/, "session identity must make retries idempotent");
assert.match(bridge, /api\.getEvents\(\)/, "persistent check-in events must participate in deduplication after reload");
assert.match(bridge, /export function collectDockTomatoStoredIdentities/, "persistent identities must use one reusable projection boundary");
assert.match(bridge, /for \(let index = 0; index < events\.length; index \+= 1\)/, "persistent identities must be collected in one complete pass");
assert.match(bridge, /const entry = ownDataValue\(events, String\(index\)\)/, "persistent identity scans must not execute array accessors or iterators");
assert.match(bridge, /exactBoundedText\(ownDataValue\(entry, "externalRef"\), 251\)/, "persisted identities must not execute corrupted record getters or accept lossy values");
assert.match(bridge, /if \(exactBoundedText\(identity, 240\)\) identities\.add\(identity\)/, "empty or oversized provider identities must not enter the dedupe set");
assert.match(bridge, /reference\.startsWith\("docktomato:"\)/, "only Dock Tomato identities may enter provider deduplication");
assert.match(bridge, /new Set\(\[\.\.\.storedIdentities, \.\.\.completedIdentities, \.\.\.inFlightIdentities\]\)/, "stored, completed and in-flight identities must share one decision boundary");
assert.match(bridge, /inFlightIdentities\.add\(identity\)[\s\S]*await host\.processDockTomatoCompletion/, "identity must enter the in-flight set before the host write starts");
assert.match(bridge, /claimedIdentity = identity/, "only the handler that starts persistence may claim the in-flight identity");
assert.match(bridge, /if \(claimedIdentity\) inFlightIdentities\.delete\(claimedIdentity\)/, "only the owning handler may release the in-flight identity");
assert.match(bridge, /throw new Error\("DOCK_TOMATO_CHECKIN_WRITE_REJECTED"\)/, "an unresolved write must remain observable and retryable");
assert.match(bridge, /dockTomatoTombstonedIdentities/, "the bridge must consult user-removed tombstones before writing");
assert.match(bridge, /user-removed/, "an undone completion must be reported as user-removed, never re-added");
assert.match(bridge, /failureItemId = item\.id/, "write failures must retain the affected item identity");
assert.match(bridge, /failureIdentity = identity/, "write failures must retain the provider session identity");
assert.match(bridge, /appendCompletionIssue\("write-failed", failureItemId, failureIdentity\)/, "write diagnostics must remain actionable");
assert.match(bridge, /resolveCompletionWriteIssue\(identity\)/, "successful retries must resolve their prior write diagnostic");
assert.match(bridge, /issue\.reason === "write-failed" && issue\.identity === identity/, "retry resolution must be scoped by reason and identity");
assert.match(bridge, /if \(bridgeDisposed\) return;[\s\S]*completedIdentities\.add/, "late writes must not recreate completion state after disposal");
assert.match(bridge, /if \(!bridgeDisposed\) \{[\s\S]*appendCompletionIssue\("write-failed"/, "late failures must not recreate diagnostics after disposal");
assert.match(bridge, /ownDataValue\(item, "archived"\) === true/, "archived-item completions must be distinguishable from duplicates");
assert.match(bridge, /ownDataValue\(item, "direction"\) === "atMost"/, "at-most goals must be rejected before accepting a completion");
assert.match(bridge, /completionClock\(ownDataValue\(detail, "completedAt"\)\)/, "completion time must pass the strict clock validation");
assert.match(bridge, /invalid-completion-time/, "a missing or invalid completedAt must be rejected instead of falling back to now");
assert.match(bridge, /durationMinutes > 1440/, "implausible forged durations must be rejected");
assert.match(bridge, /Object\.getOwnPropertyDescriptor\(object, key\)/, "foreign payload accessors must not execute during validation");
assert.match(bridge, /export function readDockTomatoRuntimeStatus/, "provider status reads must share one defensive boundary");
assert.match(bridge, /function getDockTomatoCandidate/, "provider container discovery must share one defensive boundary");
assert.match(bridge, /ownDataValue\(host, "__dockTomato"\)/, "provider container getters must not execute");
assert.match(bridge, /ownDataValue\(container, "focus"\)/, "provider facade getters must not execute");
assert.match(bridge, /getStatus\.call\(candidate\)/, "provider status methods must retain their receiver");
assert.match(bridge, /if \(!status\.readable\) return \{state: "error"/, "unreadable status must remain distinguishable");
assert.match(bridge, /ownedFocus: OwnedFocusSession \| undefined/, "the bridge must track which provider session it started");
assert.match(bridge, /interface OwnedFocusSession/, "session ownership must be a closed internal shape");
assert.match(bridge, /DOCK_TOMATO_START_UNCONFIRMED/, "an unconfirmable start result must fail closed without grabbing control");
assert.match(bridge, /invalidatedFacades\.add\(candidate\)/, "an explicit unavailable notice must invalidate the facade immediately");
assert.match(bridge, /invalidatedFacades\.delete\(candidate\)/, "an explicit available:true notice is the only way to re-enable the same object");
assert.match(bridge, /disposeAdapter\?\.\(\{stopActive: false\}\)/, "unbinding must not simulate a user stop");
assert.match(bridge, /releaseFocusAdapter\?\.\(boundAdapter\)/, "completion and ended cleanup must use the host pure-release channel");
assert.match(bridge, /capabilities\.includes\("pause-session"\)/, "session-scoped pause must be capability-gated");
assert.match(bridge, /facade\.pause\(\{sessionId: owned\.sessionId\}\)/, "the scoped pause must carry the owned session id");
assert.match(bridge, /CONTROLABLE_FOCUS_MODES/, "break phases sharing a parent session id must never be paused");
assert.match(bridge, /status\.sessionId !== owned\.sessionId/, "a foreign session must not be paused through stale ownership");
assert.match(bridge, /item\.direction !== "atMost"/, "negative at-most goals must be excluded from focus automation");
assert.match(bridge, /if \(!status\.ready\) return \{state: "not-ready"/, "provider recovery must be distinguishable from absence");
assert.match(bridge, /if \(!status\.readable\) return \{state: "error"/, "throwing provider status reads must be isolated");
assert.match(bridge, /if \(bridgeDisposed\) return;/, "queued refreshes must stop after bridge disposal");
assert.match(bridge, /const handleEnded = \(\) => \{[\s\S]*scheduleProviderRefresh\(\)/, "ended events must refresh diagnostics as well as release ownership");
assert.match(bridge, /removeEventListener\(DOCK_TOMATO_COMPLETED_EVENT/, "plugin unload must remove completion listeners");
assert.match(bridge, /tomato:focus-ended/, "manual completion or abandonment must also release the adapter state");
assert.doesNotMatch(bridge, /api\.stopFocus\(\)/, "the bridge must never release focus through the plugin-level stop");
assert.doesNotMatch(bridge, /releaseWhenIdle/, "global idle polling must stay removed: ended/completed own the lifecycle");
assert.match(preferences, /source\.focusTimerProvider === "plugin" \? "docktomato"/, "the legacy generic provider must migrate safely");
assert.match(settings, /option value="docktomato"/, "settings must expose only the named Dock Tomato provider");
assert.match(focus, /if \(adapterId\)[\s\S]*host\.focusAdapters\.get\(adapterId\)/, "named focus routing must not pick an unrelated adapter");
assert.match(bridge, /id: DOCK_TOMATO_ADAPTER_ID/, "the built-in Dock Tomato bridge must register the exact provider id");
assert.match(i18n, /底栏番茄钟插件/, "the selected provider must be explicit to users");
assert.match(bridge, /export type DockTomatoProviderState/, "provider diagnostics must use a closed state union");
for (const state of ["missing", "incompatible-version", "incomplete-api", "missing-capabilities", "not-ready", "ready", "running", "paused", "error"]) {
    assert.match(bridge, new RegExp(`state: "${state}"`), `provider diagnostics must cover ${state}`);
}
assert.match(bridge, /REQUIRED_CAPABILITIES/, "required capabilities must have one source of truth");
assert.match(bridge, /projectCapabilities\(ownDataValue\(candidate, "capabilities"\)\)/, "foreign capability values must be sanitized without executing accessors");
assert.match(bridge, /capabilities\.length < 32/, "foreign capability lists must be bounded");
assert.match(bridge, /finiteNumber\(ownDataValue\(candidate, "version"\)\)/, "invalid external version values must not leak into UI diagnostics");
assert.match(bridge, /if \(status\.paused\) return \{state: "paused"/, "paused provider state must be distinguishable");
assert.match(bridge, /if \(status\.running \|\| status\.active\) return \{state: "running"/, "running provider state must be distinguishable");
assert.match(bridge, /if \(!status\.ready\) return \{state: "not-ready"/, "provider recovery must be distinguishable from absence");
assert.match(bridge, /if \(!status\.readable\) return \{state: "error"/, "throwing provider status reads must be isolated");
assert.match(bridge, /\["ready", "running", "paused"\]\.includes\(diagnostics\.state\)/, "only healthy provider states may register an adapter");
assert.match(bridge, /onProviderStateChanged/, "provider lifecycle changes must refresh visible surfaces");
assert.match(bridge, /providerRefreshQueued/, "provider lifecycle refreshes must be coalesced");
assert.match(bridge, /Promise\.resolve\(\)\.then/, "provider refreshes must run after the current event stack");
assert.match(bridge, /if \(providerRefreshQueued \|\| bridgeDisposed\) return/, "duplicate or disposed refreshes must be ignored");
assert.match(bridge, /if \(!bridgeDisposed\) onProviderStateChanged\(\)/, "queued refreshes must recheck disposal");
assert.match(bridge, /bridgeDisposed = true;[\s\S]*removeEventListener/, "unload must invalidate queued refreshes before removing listeners");
assert.match(bridge, /tomato:focus-session-started/, "external starts must refresh provider diagnostics");
assert.match(bridge, /tomato:focus-session-paused/, "external pauses must refresh provider diagnostics");
assert.match(bridge, /removeEventListener\("tomato:focus-session-started"/, "start listeners must be removed on unload");
assert.match(bridge, /removeEventListener\("tomato:focus-session-paused"/, "pause listeners must be removed on unload");
assert.match(plugin, /dockTomatoDiagnostics: inspectDockTomatoProvider\(\)/, "settings must receive a current provider snapshot");
assert.match(plugin, /FOCUS_DIAGNOSTICS_STORAGE_NAME/, "completion diagnostics must use isolated versioned storage");
assert.match(plugin, /restoreDockTomatoCompletionIssues\(storedFocusDiagnostics\)/, "completion diagnostics must survive plugin reloads");
assert.match(plugin, /serializeDockTomatoCompletionIssues\(\)/, "completion diagnostics changes must be persisted");
assert.match(settings, /data-action="export-focus-issues"/, "settings must offer a support-safe diagnostics export");
assert.match(settings, /completionIssueCount/, "settings must report folded occurrence totals instead of row count");
assert.match(bridge, /issue\.reason === reason && issue\.itemId === safeItemId && issue\.identity === safeIdentity/, "repeated diagnostics must fold only on the full issue key");
assert.match(bridge, /Math\.min\(\(existing\?\.count \|\| 1\) \+ \(existing \? 1 : 0\), 9999\)/, "folded diagnostic counts must remain bounded");
assert.match(bridge, /const folded = new Map<string, DockTomatoCompletionIssue>\(\)/, "restored diagnostics must fold duplicate persisted rows");
assert.match(bridge, /folded\.delete\(key\)/, "restored diagnostic order must follow the newest occurrence");
assert.match(bridge, /\(existing\?\.count \|\| 0\) \+ \(issue\.count \|\| 1\)/, "restored diagnostic counts must be accumulated");
assert.match(bridge, /ownDataValue\(provider, "state"\)/, "diagnostics export must not execute provider accessors");
assert.match(bridge, /function projectCapabilities/, "provider inspection and diagnostics export must share one capability boundary");
assert.match(bridge, /Math\.min\(value\.length, 128\)/, "diagnostics capability scanning must be bounded");
assert.match(bridge, /function finiteNumber/, "provider version coercion must be isolated from hostile values");
assert.match(bridge, /Number\.isFinite\(parsedExportedAt\)/, "diagnostics export must repair invalid timestamps");
assert.match(bridge, /itemId !== item\.id/, "focus start IDs must round-trip without silent trimming or truncation");
assert.match(bridge, /itemUnit !== item\.unit/, "focus start units must round-trip without silent trimming or truncation");
assert.match(bridge, /dockTomatoError\("DOCK_TOMATO_INVALID_CONTEXT"\)/, "invalid start context must expose the stable recovery error code");
assert.match(bridge, /exactBoundedText\(ownDataValue\(detail, "sessionId"\), 240\)/, "completion identities must not be silently truncated");
assert.match(bridge, /exactBoundedText\(ownDataValue\(entry, "externalRef"\), 251\)/, "persisted focus references must round-trip exactly");
assert.match(bridge, /exactBoundedText\(identity, 240\)/, "persisted focus identities must share the completion boundary");
assert.match(bridge, /sessionId: exactBoundedText\(ownDataValue\(status, "sessionId"\), 240\)/, "runtime status identities must not be silently normalized");
assert.match(bridge, /const safeIdentity = exactBoundedText\(identity, 240\)/, "diagnostic identity keys must not be silently normalized");
assert.match(bridge, /const itemId = exactBoundedText\(ownDataValue\(value, "itemId"\), 160\)/, "restored diagnostic item identities must remain lossless");
assert.match(bridge, /const scanStart = Math\.max\(0, entries\.length - 512\)/, "diagnostic restore scanning must remain bounded");
assert.match(bridge, /normalizeCompletionIssue\(ownDataValue\(entries, String\(index\)\)\)/, "diagnostic restore must not execute array accessors");
assert.match(bridge, /const rawCount = finiteNumber\(ownDataValue\(value, "count"\)\)/, "diagnostic count coercion must isolate hostile values");
assert.match(bridge, /COMPLETION_ISSUE_ARCHIVE_MAX_CHARS = 512 \* 1024/, "diagnostic JSON input must have an explicit size ceiling");
assert.match(bridge, /value\.length <= COMPLETION_ISSUE_ARCHIVE_MAX_CHARS/, "oversized diagnostic JSON must be rejected before parsing");
assert.match(bridge, /function findCompletionItem/, "completion item lookup must use one defensive boundary");
assert.match(bridge, /const candidate = ownDataValue\(items, String\(index\)\)/, "completion item lookup must not execute array accessors");
assert.match(bridge, /ownDataValue\(candidate, "id"\) === itemId/, "completion item lookup must not execute item identity accessors");
assert.match(bridge, /exactBoundedText\(ownDataValue\(context, "itemId"\), 160\)/, "completion item context must round-trip exactly");
assert.match(bridge, /exactBoundedText\(ownDataValue\(context, "itemUnit"\), 80\)/, "completion unit context must round-trip exactly");
assert.match(bridge, /typeof rawDuration === "number" && Number\.isFinite\(rawDuration\)/, "completion duration must not execute coercion hooks");
assert.match(plugin, /downloadDockTomatoDiagnosticsFor\(inspectDockTomatoProvider\(\)\)/, "exports must capture a current provider snapshot");
assert.match(i18n, /"set\.tomatoIssueExport": "导出诊断"/, "Chinese diagnostics export copy must exist");
assert.match(i18n, /"set\.tomatoIssueExport": "Export diagnostics"/, "English diagnostics export copy must exist");
assert.match(plugin, /data-action='use-builtin-focus'/, "the unavailable-provider recovery action must be bound");
assert.match(plugin, /this\.focusTimerProvider = "builtin"/, "recovery must explicitly select the built-in provider");
assert.match(plugin, /set\.tomatoFallbackSaved/, "provider fallback must give user feedback");
assert.match(settings, /Record<DockTomatoProviderState, string>/, "every diagnostic state must map to localized copy");
assert.match(settings, /data-focus-provider-state/, "diagnostic state must be inspectable in rendered UI");
assert.match(settings, /role="status"/, "diagnostic changes must be announced accessibly");
assert.match(settings, /ctx\.focusTimerProvider === "docktomato" && !tomatoHealthy/, "fallback must only appear for an unhealthy selected provider");
assert.match(settings, /set\.tomatoDiagnosticVersion/, "detected API versions must be explained");
assert.match(settings, /set\.tomatoDiagnosticInstall/, "missing providers must receive installation guidance");
assert.match(i18n, /"set\.tomatoStateMissing": "未安装或未启用"/, "Chinese copy must distinguish missing providers");
assert.match(i18n, /"set\.tomatoStateVersion": "版本不兼容"/, "Chinese copy must distinguish incompatible versions");
assert.match(i18n, /"set\.tomatoStateCapabilities": "缺少所需能力"/, "Chinese copy must distinguish missing capabilities");
assert.match(i18n, /"set\.tomatoUseBuiltin": "改用自带番茄钟"/, "Chinese recovery action must be explicit");
assert.match(i18n, /"set\.tomatoStateMissing": "Not installed or disabled"/, "English copy must distinguish missing providers");
assert.match(i18n, /"set\.tomatoStateError": "Could not read status"/, "English copy must distinguish status failures");
assert.match(i18n, /"set\.tomatoUseBuiltin": "Use built-in timer"/, "English recovery action must be explicit");
assert.match(today, /DOCK_TOMATO_MESSAGE_KEYS: Record<DockTomatoProviderState, string>/, "Today must map every provider state to an actionable message");
assert.match(today, /inspectDockTomatoProvider\(\)\.state/, "Today must inspect the current provider state at click time");
/* 收件箱与宿主回写通道（D-227）。 */
assert.match(inbox, /export function completionClock/, "the completion clock must live in one pure boundary");
assert.match(inbox, /export function dockTomatoCompletionValue/, "completion value conversion must share one boundary");
assert.match(inbox, /export function normalizeInboxStore/, "the inbox must have one corruption-isolating restore path");
assert.match(inbox, /DOCKTOMATO_INBOX_CAPACITY/, "the inbox must have an explicit capacity");
assert.match(inbox, /INBOX_RETRY_DELAYS_MS: readonly number\[\] = \[1000, 5000, 30000\]/, "retry pacing must be explicit and bounded");
assert.match(inbox, /outcome: "conflict"/, "conflicting payloads must not overwrite the first received data");
assert.match(plugin, /DOCKTOMATO_INBOX_STORAGE_NAME = "checkin-docktomato-inbox"/, "the pending completion inbox must use isolated versioned storage");
assert.match(plugin, /processDockTomatoCompletion: \(entry\) => this\.processDockTomatoCompletion\(entry\)/, "the bridge host must wire the host-owned write channel");
assert.match(plugin, /dockTomatoTombstonedIdentities: \(\) => this\.collectDockTomatoTombstonedIdentities\(\)/, "the bridge host must expose the tombstone projection");
assert.match(plugin, /recordDockTomatoCompletionUnlocked/, "the writer must run inside the already-held storage lock");
assert.match(plugin, /reconcileDockTomatoInbox/, "pending completions must recover after reload");
assert.match(plugin, /dockTomatoInboxTimer !== undefined/, "the retry wake timer must be cleared on unload");
assert.match(i18n, /"set\.tomatoIssueSkippedDay"/, "Chinese copy must explain skipped-day blocking");
assert.match(i18n, /"set\.tomatoIssueAtMost"/, "Chinese copy must explain at-most blocking");
assert.match(i18n, /"set\.tomatoIssueUserRemoved"/, "Chinese copy must explain user-removed completions");
assert.match(i18n, /"set\.tomatoIssueSkippedDay": "The completion date is marked as skipped/, "English copy must explain skipped-day blocking");
assert.match(i18n, /"msg\.dockInboxFull"/, "Chinese or English copy must explain inbox capacity");
for (const key of ["focusDockMissing", "focusDockVersion", "focusDockApi", "focusDockCapabilities", "focusDockLoading", "focusDockBusy", "focusDockPaused", "focusDockError"]) {
    assert.match(today, new RegExp(`msg\\.${key}`), `Today must handle ${key}`);
}
assert.match(focus, /export function focusStartErrorMessage/, "start failures must pass through a stable error translator");
assert.match(focus, /DOCK_TOMATO_NOT_READY/, "not-ready errors must be translated");
assert.match(focus, /DOCK_TOMATO_TIMER_BUSY/, "busy errors must be translated");
assert.match(focus, /DOCK_TOMATO_INVALID_CONTEXT/, "invalid-context errors must be translated");
assert.match(focus, /DOCK_TOMATO_START_UNCONFIRMED/, "unconfirmed-start errors must be translated");
assert.match(focus, /DOCK_TOMATO_SESSION_MISMATCH/, "session-mismatch errors must be translated");
assert.match(focus, /DOCK_TOMATO_INTEGRATION_DISABLED/, "integration-disabled errors must be translated");
assert.match(focus, /export function releaseFocusAdapterFor/, "the host must expose one pure release boundary");
assert.match(focus, /focusMappingFingerprint/, "focus ownership validation must include the mapping fingerprint");
assert.match(plugin, /releaseFocusAdapter: \(adapter\) => releaseFocusAdapterFor/, "the bridge host must wire the pure release channel");
assert.match(plugin, /activeFocusAdapter\.id !== DOCK_TOMATO_ADAPTER_ID/, "unloading must not pause the cross-plugin timer (D-226)");
assert.match(i18n, /"msg\.focusDockUnconfirmed": "底栏番茄钟未返回可确认的会话身份/, "Chinese unconfirmed-start copy must exist");
assert.match(i18n, /"msg\.focusDockSessionMismatch": "底栏番茄钟的当前会话已变化/, "Chinese session-mismatch copy must exist");
assert.match(i18n, /"msg\.focusDockDisabled": "底栏番茄钟的第三方联动开关已关闭/, "Chinese disabled copy must exist");
assert.match(i18n, /"msg\.focusDockUnconfirmed": "Dock Tomato did not return a confirmable session identity/, "English unconfirmed-start copy must exist");
assert.match(i18n, /"msg\.focusDockSessionMismatch": "Dock Tomato moved on to a different session/, "English session-mismatch copy must exist");
assert.match(i18n, /"msg\.focusDockDisabled": "Dock Tomato third-party integration is disabled/, "English disabled copy must exist");
assert.match(focus, /detail\.slice\(0, 240\)/, "unrecognized provider errors must be bounded before display");
assert.match(focus, /catch \{ detail = t\("common\.unknownError"\); \}/, "hostile error objects must not escape error rendering");
assert.match(i18n, /"msg\.focusDockMissing": "未检测到底栏番茄钟/, "Chinese missing-provider guidance must be actionable");
assert.match(i18n, /"msg\.focusDockPaused": "底栏番茄钟有暂停中的专注/, "Chinese paused guidance must be actionable");
assert.match(i18n, /"msg\.focusDockMissing": "Dock Tomato was not detected/, "English missing-provider guidance must be actionable");
assert.match(i18n, /"msg\.focusDockPaused": "Dock Tomato has a paused focus session/, "English paused guidance must be actionable");

console.log("Dock Tomato integration contract checks passed.");
