const assert = require("node:assert/strict");
const fs = require("node:fs");

const bridge = fs.readFileSync("src/dock-tomato.ts", "utf8");
const preferences = fs.readFileSync("src/view-preferences.ts", "utf8");
const settings = fs.readFileSync("src/render/settings.ts", "utf8");
const focus = fs.readFileSync("src/render/focus-adapter.ts", "utf8");
const today = fs.readFileSync("src/render/bind-today.ts", "utf8");
const i18n = fs.readFileSync("src/i18n.ts", "utf8");
const plugin = fs.readFileSync("src/index.ts", "utf8");

assert.match(bridge, /apiVersion !== 1/, "unknown Dock Tomato API versions must be rejected");
assert.match(bridge, /\["status", "start", "pause", "completion-event"\]/, "declared capabilities must be negotiated when present");
assert.match(bridge, /tomato:focus-api-availability-changed/, "either plugin load order must be supported");
assert.match(bridge, /tomato:focus-session-completed/, "durable completion events must be consumed");
assert.match(bridge, /externalRef: `docktomato:\$\{identity\}`/, "session identity must make retries idempotent");
assert.match(bridge, /api\.getEvents\(\)/, "persistent check-in events must participate in deduplication after reload");
assert.match(bridge, /reference\.startsWith\("docktomato:"\)/, "only Dock Tomato identities may enter provider deduplication");
assert.match(bridge, /new Set\(\[\.\.\.storedIdentities, \.\.\.completedIdentities, \.\.\.inFlightIdentities\]\)/, "stored, completed and in-flight identities must share one decision boundary");
assert.match(bridge, /if \(!recorded\) throw new Error\("DOCK_TOMATO_CHECKIN_WRITE_REJECTED"\)/, "an empty write result must remain observable and retryable");
assert.match(bridge, /item\.unit === "小时" \? durationMinutes \/ 60 : durationMinutes/, "minutes must convert to hour-based items");
assert.match(bridge, /item\.tomatoMode === "sessions"\) return 1/, "session-mode items must record one completion");
assert.match(bridge, /durationMinutes > 1440/, "implausible forged durations must be rejected");
assert.match(bridge, /Object\.getOwnPropertyDescriptor\(object, key\)/, "foreign payload accessors must not execute during validation");
assert.match(bridge, /export function readDockTomatoRuntimeStatus/, "provider status reads must share one defensive boundary");
assert.match(bridge, /getStatus\.call\(candidate\)/, "provider status methods must retain their receiver");
assert.match(bridge, /if \(!status\.readable\) return \{state: "error"/, "unreadable status must remain distinguishable");
assert.match(bridge, /if \(bridgeDisposed\) return;/, "release polling must stop after bridge disposal");
assert.match(bridge, /status\.readable && !status\.active/, "unreadable status must not prematurely release focus ownership");
assert.match(bridge, /status\.readable && status\.ready && !status\.active/, "canStart must fail closed on unreadable status");
assert.match(bridge, /const handleEnded = \(\) => \{[\s\S]*scheduleProviderRefresh\(\)/, "ended events must refresh diagnostics as well as release ownership");
assert.match(bridge, /removeEventListener\(DOCK_TOMATO_COMPLETED_EVENT/, "plugin unload must remove completion listeners");
assert.match(bridge, /releaseWhenIdle\(remaining - 1\), 250/, "adapter state must only release after Dock Tomato becomes idle");
assert.match(bridge, /tomato:focus-ended/, "manual completion or abandonment must also release the adapter state");
assert.match(preferences, /source\.focusTimerProvider === "plugin" \? "docktomato"/, "the legacy generic provider must migrate safely");
assert.match(settings, /option value="docktomato"/, "settings must expose only the named Dock Tomato provider");
assert.match(focus, /if \(adapterId\)[\s\S]*host\.focusAdapters\.get\(adapterId\)/, "named focus routing must not pick an unrelated adapter");
assert.match(bridge, /id: DOCK_TOMATO_ADAPTER_ID/, "the built-in Dock Tomato bridge must register the exact provider id");
assert.match(i18n, /底栏番茄钟插件/, "the selected provider must be explicit to users");
assert.match(bridge, /export type DockTomatoProviderState/, "provider diagnostics must use a closed state union");
for (const state of ["missing", "incompatible-version", "incomplete-api", "missing-capabilities", "not-ready", "ready", "running", "paused", "error"]) {
    assert.match(bridge, new RegExp(`state: "${state}"`), `provider diagnostics must cover ${state}`);
}
assert.match(bridge, /REQUIRED_CAPABILITIES/, "required capabilities must have one source of truth");
assert.match(bridge, /rawCapabilities\.filter/, "foreign capability values must be sanitized");
assert.match(bridge, /slice\(0, 32\)/, "foreign capability lists must be bounded");
assert.match(bridge, /Number\.isFinite\(parsedVersion\)/, "invalid external version values must not leak into UI diagnostics");
assert.match(bridge, /if \(status\.paused\) return \{state: "paused"/, "paused provider state must be distinguishable");
assert.match(bridge, /if \(status\.running \|\| status\.active\) return \{state: "running"/, "running provider state must be distinguishable");
assert.match(bridge, /if \(!status\.ready\) return \{state: "not-ready"/, "provider recovery must be distinguishable from absence");
assert.match(bridge, /if \(!status\.readable\) return \{state: "error"/, "throwing provider status reads must be isolated");
assert.match(bridge, /\["ready", "running", "paused"\]\.includes\(diagnostics\.state\)/, "only healthy provider states may register an adapter");
assert.match(bridge, /onProviderStateChanged/, "provider lifecycle changes must refresh visible surfaces");
assert.match(bridge, /providerRefreshQueued/, "provider lifecycle refreshes must be coalesced");
assert.match(bridge, /Promise\.resolve\(\)\.then/, "provider refreshes must run after the current event stack");
assert.match(bridge, /if \(providerRefreshQueued \|\| bridgeDisposed\) return/, "duplicate or disposed refreshes must be ignored");
assert.match(bridge, /if \(!bridgeDisposed\) onProviderStateChanged\(\)/, "queued refreshes must recheck disposal");
assert.match(bridge, /bridgeDisposed = true;[\s\S]*removeEventListener/, "unload must invalidate queued refreshes before removing listeners");
assert.match(bridge, /tomato:focus-session-started/, "external starts must refresh provider diagnostics");
assert.match(bridge, /tomato:focus-session-paused/, "external pauses must refresh provider diagnostics");
assert.match(bridge, /removeEventListener\("tomato:focus-session-started"/, "start listeners must be removed on unload");
assert.match(bridge, /removeEventListener\("tomato:focus-session-paused"/, "pause listeners must be removed on unload");
assert.match(plugin, /dockTomatoDiagnostics: inspectDockTomatoProvider\(\)/, "settings must receive a current provider snapshot");
assert.match(plugin, /FOCUS_DIAGNOSTICS_STORAGE_NAME/, "completion diagnostics must use isolated versioned storage");
assert.match(plugin, /restoreDockTomatoCompletionIssues\(storedFocusDiagnostics\)/, "completion diagnostics must survive plugin reloads");
assert.match(plugin, /serializeDockTomatoCompletionIssues\(\)/, "completion diagnostics changes must be persisted");
assert.match(settings, /data-action="export-focus-issues"/, "settings must offer a support-safe diagnostics export");
assert.match(plugin, /downloadDockTomatoDiagnosticsFor\(inspectDockTomatoProvider\(\)\)/, "exports must capture a current provider snapshot");
assert.match(i18n, /"set\.tomatoIssueExport": "导出诊断"/, "Chinese diagnostics export copy must exist");
assert.match(i18n, /"set\.tomatoIssueExport": "Export diagnostics"/, "English diagnostics export copy must exist");
assert.match(plugin, /data-action='use-builtin-focus'/, "the unavailable-provider recovery action must be bound");
assert.match(plugin, /this\.focusTimerProvider = "builtin"/, "recovery must explicitly select the built-in provider");
assert.match(plugin, /set\.tomatoFallbackSaved/, "provider fallback must give user feedback");
assert.match(settings, /Record<DockTomatoProviderState, string>/, "every diagnostic state must map to localized copy");
assert.match(settings, /data-focus-provider-state/, "diagnostic state must be inspectable in rendered UI");
assert.match(settings, /role="status"/, "diagnostic changes must be announced accessibly");
assert.match(settings, /ctx\.focusTimerProvider === "docktomato" && !tomatoHealthy/, "fallback must only appear for an unhealthy selected provider");
assert.match(settings, /set\.tomatoDiagnosticVersion/, "detected API versions must be explained");
assert.match(settings, /set\.tomatoDiagnosticInstall/, "missing providers must receive installation guidance");
assert.match(i18n, /"set\.tomatoStateMissing": "未安装或未启用"/, "Chinese copy must distinguish missing providers");
assert.match(i18n, /"set\.tomatoStateVersion": "版本不兼容"/, "Chinese copy must distinguish incompatible versions");
assert.match(i18n, /"set\.tomatoStateCapabilities": "缺少所需能力"/, "Chinese copy must distinguish missing capabilities");
assert.match(i18n, /"set\.tomatoUseBuiltin": "改用自带番茄钟"/, "Chinese recovery action must be explicit");
assert.match(i18n, /"set\.tomatoStateMissing": "Not installed or disabled"/, "English copy must distinguish missing providers");
assert.match(i18n, /"set\.tomatoStateError": "Could not read status"/, "English copy must distinguish status failures");
assert.match(i18n, /"set\.tomatoUseBuiltin": "Use built-in timer"/, "English recovery action must be explicit");
assert.match(today, /DOCK_TOMATO_MESSAGE_KEYS: Record<DockTomatoProviderState, string>/, "Today must map every provider state to an actionable message");
assert.match(today, /inspectDockTomatoProvider\(\)\.state/, "Today must inspect the current provider state at click time");
for (const key of ["focusDockMissing", "focusDockVersion", "focusDockApi", "focusDockCapabilities", "focusDockLoading", "focusDockBusy", "focusDockPaused", "focusDockError"]) {
    assert.match(today, new RegExp(`msg\\.${key}`), `Today must handle ${key}`);
}
assert.match(focus, /export function focusStartErrorMessage/, "start failures must pass through a stable error translator");
assert.match(focus, /DOCK_TOMATO_NOT_READY/, "not-ready errors must be translated");
assert.match(focus, /DOCK_TOMATO_TIMER_BUSY/, "busy errors must be translated");
assert.match(focus, /DOCK_TOMATO_INVALID_CONTEXT/, "invalid-context errors must be translated");
assert.match(focus, /detail\.slice\(0, 240\)/, "unrecognized provider errors must be bounded before display");
assert.match(focus, /catch \{ detail = t\("common\.unknownError"\); \}/, "hostile error objects must not escape error rendering");
assert.match(i18n, /"msg\.focusDockMissing": "未检测到底栏番茄钟/, "Chinese missing-provider guidance must be actionable");
assert.match(i18n, /"msg\.focusDockPaused": "底栏番茄钟有暂停中的专注/, "Chinese paused guidance must be actionable");
assert.match(i18n, /"msg\.focusDockMissing": "Dock Tomato was not detected/, "English missing-provider guidance must be actionable");
assert.match(i18n, /"msg\.focusDockPaused": "Dock Tomato has a paused focus session/, "English paused guidance must be actionable");

console.log("Dock Tomato integration contract checks passed.");
