const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const ts = require("typescript");
const source = fs.readFileSync("src/ecosystem.ts", "utf8");
const output = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "siyuan-ecosystem-")), "ecosystem.js");
fs.writeFileSync(output, ts.transpileModule(source, {compilerOptions: {target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS}}).outputText);
const api = require(output);
const record = api.normalizeExternalRecord({itemId: "run", value: 2, unit: "公里", source: "tomato", externalRef: "session-1", note: "完成"});
assert.equal(record.source, "tomato"); assert.equal(record.value, 2); assert.equal(api.hasExternalRecord([{source: "tomato", externalRef: "session-1"}], record), true);
assert.equal(api.normalizeExternalRecord({itemId: "run", value: -1, source: "x", externalRef: "bad"}), undefined);
assert.equal(api.normalizeExternalRecord({itemId: "run", value: 1, source: "x"}), undefined);
assert.equal(api.normalizeExternalRecord({itemId: "run", value: 1, externalRef: "x"}).source, "external");
const registry = api.createIntegrationRegistry();
const adapter = {id: "tomato", name: "番茄钟", capabilities: ["record"], normalize: (input) => api.normalizeExternalRecord(input, "tomato")};
const dispose = registry.register(adapter);
assert.equal(registry.list().length, 1);
assert.equal(registry.normalize("tomato", {itemId: "run", value: 1, externalRef: "s1"}).source, "tomato");
dispose();
assert.equal(registry.list().length, 0);
assert.equal(api.isIntegrationAdapter(adapter), true);
assert.equal(api.isIntegrationAdapter({...adapter, capabilities: ["unknown"]}), false);
assert.equal(api.isIntegrationAdapter({...adapter, capabilities: []}), false);
registry.register({...adapter, id: "bad", capabilities: ["unknown"]});
assert.equal(registry.list().length, 0);
const completion = api.completionToRecord({id: "task-42", source: "tasks", itemId: "run", completedAt: "2026-09-09T08:00:00+08:00", title: "晨跑"});
assert.equal(completion.externalRef, "tasks:task-42");
assert.equal(completion.value, 1);
assert.match(completion.note, /晨跑/);
assert.equal(api.completionToRecord({id: "x", source: "tasks", itemId: "run", completedAt: "invalid"}), undefined);
assert.equal(api.integrationKey({source: " tasks ", externalRef: " task-42 "}), "tasks::task-42");
const unsupported = api.probeAgentCapabilityHost({}); assert.equal(unsupported.supported, false); assert.equal(unsupported.register({}).registered, false);
const supported = api.probeAgentCapabilityHost({addAgentCapability: () => "ok"}); assert.equal(supported.supported, true); assert.equal(supported.register({name: "demo"}).registered, true);
const failing = api.probeAgentCapabilityHost({addAgentCapability: () => { throw new Error("blocked"); }}); assert.equal(failing.register({}).error, "blocked");
const registered = api.registerAgentCapabilities(supported, [{name: "summary"}, {name: "record", effects: {localWrite: true, localRead: false}}, {name: "insight"}]); assert.deepEqual(registered.registered, ["summary", "insight"]); assert.deepEqual(registered.skipped, ["record"]);
api.safeAgentCall(() => "ok").then((result) => { assert.deepEqual(result, {ok: true, value: "ok"}); return api.safeAgentCall(() => { throw new Error("offline"); }); }).then((result) => { assert.equal(result.offline, true); assert.equal(result.error, "offline"); console.log("Integration ecosystem checks passed."); fs.rmSync(path.dirname(output), {recursive: true, force: true}); });
