const assert = require("node:assert/strict");
const fs = require("node:fs");
const source = fs.readFileSync("src/index.ts", "utf8");
const sharedSource = fs.readFileSync("src/shared.ts", "utf8");
const agentSource = fs.readFileSync("src/agent-capabilities.ts", "utf8");
const manifest = JSON.parse(fs.readFileSync("plugin.json", "utf8"));
const packageManifest = JSON.parse(fs.readFileSync("package.json", "utf8"));
assert.equal(manifest.version, packageManifest.version, "plugin and package versions must stay aligned");
assert.equal(manifest.minAppVersion >= "3.4.2", true);

assert.match(source, /this\.isMobileFrontend = frontend === "mobile" \|\| frontend === "browser-mobile"/);
assert.match(source, /this\.supportsCustomTab = !this\.isMobileFrontend/);
assert.match(source, /if \(this\.supportsCustomTab\) this\.addCommand/);
assert.match(source, /if \(!this\.supportsCustomTab\) this\.openQuickDialog\(\)/);
const fragmentsSource = fs.readFileSync("src/render/fragments.ts", "utf8");
assert.match(fragmentsSource, /data-action="open-tab"/);
assert.match(source, /getCustomSummaryContext/);
assert.match(source, /自定义总结范围无效/);
assert.match(source, /CHECKIN_API_VERSION/);
assert.match(source, /summarizeCustom: \(range, providerId\) => summarizeWithProvider\("day", range, providerId\)/);
assert.match(source, /customRange \? buildCustomSummaryContext/);
assert.match(source, /getEventsInCustomRange\(this\.store, customRange\)/);
assert.match(source, /const SUMMARY_TIMEOUT_MS = 30000/);
assert.match(source, /withTimeout\(provider\.summarize\([\s\S]*SUMMARY_TIMEOUT_MS, "总结适配器响应超时"/);
assert.match(sharedSource, /export function withTimeout<T>\(promise: Promise<T>, timeoutMs: number, message: string\)/);
assert.match(source, /addAgentCapability\?:/);
assert.match(agentSource, /checkin-summary-context/);
assert.match(agentSource, /checkin-list-items/);
assert.match(agentSource, /checkin-item-insights/);
assert.match(agentSource, /checkin-record-event/);
assert.match(agentSource, /checkin-list-occasions/);
assert.match(agentSource, /checkin-complete-occasion/);
assert.match(source, /ensureSpeedSwitchQuickActions/);
assert.match(source, /\(this\.app as unknown as \{plugins\?: unknown\} \| undefined\)\?\.plugins/,
    "optional launcher discovery must tolerate hosts without an app plugin registry");
assert.match(source, /lcCheckinMobileTopBarButton/);
assert.match(agentSource, /localRead: true, dataEgress: true, externalCost: false/);
assert.match(agentSource, /localRead: true, localWrite: true, dataEgress: true, externalCost: false/);
assert.match(agentSource, /required: \["itemId"\]/);
assert.match(agentSource, /今日可用的打卡项目/);
assert.match(agentSource, /buildCoachingSuggestions\(report\)/);
assert.match(agentSource, /suggestions,/);
assert.match(agentSource, /自定义日期范围无效，请使用 YYYY-MM-DD/);
console.log("Entry capability structure checks passed.");
