const assert = require("node:assert/strict");
const fs = require("node:fs");
const source = fs.readFileSync("src/index.ts", "utf8");
const i18n = fs.readFileSync("src/i18n.ts", "utf8");
assert.match(source, /lc-checkin lc-checkin--history lc-checkin--insights[\s\S]*t\("insights\.empty"\)/);
assert.match(i18n, /"insights\.empty": "没有可复盘的打卡项"/);
assert.match(source, /role="list" aria-label="\$\{t\("insights\.window"\)\}"/);
assert.match(source, /role="listitem" tabindex="0"/);
assert.match(source, /day\.status === "complete"/);
assert.match(source, /role="list" aria-label="\$\{t\("insights\.legendAria"\)\}"/);
assert.match(i18n, /"insights\.partial": "部分完成"/);
assert.match(i18n, /"insights\.missed": "未完成"/);
console.log("Insight accessibility structure checks passed.");
