const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
const i18nSource = fs.readFileSync(path.join(__dirname, "..", "src", "i18n.ts"), "utf8");

assert.match(i18nSource, /"schedule\.interval": "每隔 N 天"/);
assert.match(i18nSource, /"schedule\.quota": "周期配额"/);
assert.match(source, /name="intervalDays"[^>]*min="1"[^>]*max="3650"/);
assert.match(source, /name="anchorDate"[^>]*type="date"/);
assert.match(source, /intervalSchedule\.hidden = scheduleSelect\?\.value !== "interval"/);
assert.match(source, /scheduleType === "interval"[\s\S]*intervalDays: intervalDaysValue, anchorDate: anchorDateValue/);
assert.match(source, /scheduleType === "quota"[\s\S]*quota: \{period: requestedQuotaPeriod, amount: Math\.round\(quotaAmountValue \* 100\) \/ 100, countMode: requestedQuotaMode/);
assert.match(source, /name="quotaPeriod"/);
assert.match(source, /name="quotaCountMode"/);
assert.match(source, /quotaSchedule\.hidden = scheduleSelect\?\.value !== "quota"/);
assert.match(source, /formatScheduleLabel\(revision\.schedule\)/);
assert.match(source, /revision\.kind === "binary" && revision\.schedule\.type !== "quota"/);
assert.match(source, /isValidLocalDateInput\(requestedAnchor\)/);
assert.match(source, /Math\.ceil\(current \/ step - 1e-9\) \* step/);
assert.match(source, /data-editor-preview/);
assert.match(source, /updateEditorPreview/);
assert.match(source, /data-preview-action/);
assert.match(source, /data-action="save-template"/);
assert.match(source, /保存为我的模板/);
assert.match(source, /!weekdays\.querySelector<HTMLInputElement>\("input\[name='weekday'\]:checked"\)/);
assert.match(source, /const advanced = root\.querySelector<HTMLDetailsElement>\("\[data-advanced\]"\)/);
assert.match(source, /name="completionSource"/);
assert.match(source, /name="tomatoMode"/);
assert.match(source, /data-tomato-mode-field/);
assert.match(source, /source=tomato/);
assert.match(source, /completionSource: data\.get\("completionSource"\) === "tomato"/);
assert.match(source, /data-custom-icon-file/);
assert.match(source, /data-custom-icon-library/);
assert.match(source, /data-action="open-iconfont"/);
assert.match(source, /data-action='download-custom-icon'/);
assert.match(source, /normalizeCustomIconLibrary/);

console.log("Interval editor structure checks passed.");
