const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const legacy = fs.readFileSync(path.join(root, "src", "index.scss"), "utf8");
const components = fs.readFileSync(path.join(root, "src", "ui", "components.scss"), "utf8");
const entry = fs.readFileSync(path.join(root, "src", "index.ts"), "utf8");
assert.ok(legacy.length > 0, "legacy floor stylesheet must remain available");
assert.doesNotMatch(components, /--b3-[\w-]+/, "component layer must stay independent from host tokens");
assert.doesNotMatch(legacy, /@(?:media|container)[^{]+\{\s*\}/, "legacy stylesheet must not keep empty responsive blocks");
assert.doesNotMatch(legacy, /Fourteenth narrow-surface pass|Fifteenth narrow-surface pass/, "retired migration markers must not remain in legacy stylesheet");
assert.ok(entry.indexOf('import "./ui/tokens.scss";') < entry.indexOf('import "./index.scss";'), "tokens must load before legacy floor styles");
assert.ok(entry.indexOf('import "./index.scss";') < entry.indexOf('import "./ui/components.scss";'), "component styles must load after legacy floor styles");
assert.ok(!legacy.includes(".lc-checkin__preview-card {"), "preview foundation must stay retired from legacy layer");
assert.ok(!legacy.includes(".lc-checkin__history-row {"), "history row foundation must stay retired from legacy layer");
assert.ok(!legacy.includes(".lc-checkin__history-event-actions {"), "history action layout must stay retired from legacy layer");
assert.match(components, /\.lc-checkin__editor-actions \{/, "editor actions must have a component-layer owner");
assert.match(components, /\.lc-checkin__history-event-actions \{/, "history actions must have a component-layer owner");
console.log("Legacy style audit passed: retired foundations stay out of index.scss.");
