const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const legacy = fs.readFileSync(path.join(root, "src", "index.scss"), "utf8");
const components = fs.readFileSync(path.join(root, "src", "ui", "components.scss"), "utf8");
const tokens = fs.readFileSync(path.join(root, "src", "ui", "tokens.scss"), "utf8");
const plugin = fs.readFileSync(path.join(root, "src", "index.ts"), "utf8");
assert.ok(legacy.length > 0, "legacy floor stylesheet must remain available");
assert.doesNotMatch(components, /--b3-[\w-]+/, "component layer must stay independent from host tokens");
assert.doesNotMatch(legacy, /@(?:media|container)[^{]+\{\s*\}/, "legacy stylesheet must not keep empty responsive blocks");
assert.doesNotMatch(legacy, /Fourteenth narrow-surface pass|Fifteenth narrow-surface pass/, "retired migration markers must not remain in legacy stylesheet");
assert.ok(!legacy.includes(".lc-checkin__preview-card {"), "preview foundation must stay retired from legacy layer");
assert.ok(!legacy.includes(".lc-checkin__history-row {"), "history row foundation must stay retired from legacy layer");
assert.ok(!legacy.includes(".lc-checkin__history-event-actions {"), "history action layout must stay retired from legacy layer");
assert.doesNotMatch(legacy, /@media \(hover: none\), \(pointer: coarse\)/, "coarse-pointer behavior must stay retired from legacy layer");
assert.doesNotMatch(legacy, /@media \(prefers-reduced-motion: reduce\)/, "reduced-motion behavior must stay retired from legacy layer");
assert.doesNotMatch(legacy, /@media print/, "print behavior must stay retired from legacy layer");
assert.doesNotMatch(legacy, /:root\s*\{/, "design tokens must stay retired from legacy layer");
assert.doesNotMatch(legacy, /\.lc-checkin__organize\s*\{/, "organize foundations must stay retired from legacy layer");
assert.doesNotMatch(legacy, /\.lc-checkin__range-tabs\s*\{/, "range tab foundations must stay retired from legacy layer");
assert.doesNotMatch(legacy, /\.lc-checkin__summary-stats\s*\{/, "review summary foundations must stay retired from legacy layer");
assert.doesNotMatch(legacy, /\.lc-checkin__section-heading\s*[,\{]/, "section heading foundations must stay retired from legacy layer");
assert.doesNotMatch(legacy, /\.lc-checkin__form-scroll\s*>/, "editor panel foundations must stay retired from legacy layer");
assert.doesNotMatch(legacy, /\.lc-checkin__mobile-nav\s*\{/, "mobile navigation foundations must stay retired from legacy layer");
assert.doesNotMatch(legacy, /\.lc-template-manager\s*\{/, "template manager foundations must stay retired from legacy layer");
assert.match(components, /\.lc-template-manager\s*\{[\s\S]*background:\s*var\(--lc-checkin-bg\)/, "template manager foundations must have a component-layer owner");
assert.match(components, /\.lc-checkin__organize[\s\S]*background:\s*var\(--lc-checkin-muted-surface\)/, "organize foundations must have a component-layer owner");
assert.match(tokens, /--lc-checkin-control-height:\s*36px/, "control geometry must have a token-layer owner");
assert.doesNotMatch(plugin, /import "\.\/index\.scss"/, "retired legacy stylesheet must not remain in the production bundle");
assert.match(components, /@media \(hover: none\), \(pointer: coarse\)/, "coarse-pointer behavior must have a component-layer owner");
assert.match(components, /@media print/, "print behavior must have a component-layer owner");
assert.match(components, /\.lc-checkin__editor-actions \{/, "editor actions must have a component-layer owner");
assert.match(components, /\.lc-checkin__history-event-actions \{/, "history actions must have a component-layer owner");
console.log("Legacy style audit passed: retired foundations stay out of index.scss.");
