const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const ts = require("typescript");
const source = fs.readFileSync("src/occasions.ts", "utf8");
const indexSource = fs.readFileSync("src/index.ts", "utf8");

assert.match(source, /getVisibleOccasions/);
assert.match(source, /remindBeforeDays/);
assert.match(source, /recurrence === "once"/);
assert.match(source, /markOccasionCompleted/);
assert.match(source, /completedDates/);
const output = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "siyuan-occasions-")), "occasions.js");
const compilerOptions = {target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS};
fs.writeFileSync(output, ts.transpileModule(source, {compilerOptions}).outputText);
fs.writeFileSync(path.join(path.dirname(output), "lunar.js"), ts.transpileModule(fs.readFileSync("src/lunar.ts", "utf8"), {compilerOptions}).outputText);
fs.writeFileSync(path.join(path.dirname(output), "i18n.js"), ts.transpileModule(fs.readFileSync("src/i18n.ts", "utf8"), {compilerOptions}).outputText);
const occasions = require(output);
const annual = occasions.normalizeOccasion({id: "birthday", name: "妈妈生日", kind: "birthday", date: "2026-09-12", recurrence: "annual", remindBeforeDays: 3, enabled: true});
assert.equal(annual.date, "2026-09-12");
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [annual]}, new Date(2026, 8, 9, 12))[0].daysUntil, 3);
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [annual]}, new Date(2026, 8, 12, 12))[0].status, "today");
const completed = occasions.markOccasionCompleted({version: 1, occasions: [annual]}, "birthday", "2026-09-12", true);
assert.equal(occasions.isOccasionCompleted(completed.occasions[0], "2026-09-12"), true);
const once = occasions.normalizeOccasion({id: "loan", name: "还房贷", kind: "scheduled", date: "2026-09-15", recurrence: "once", remindBeforeDays: 2, enabled: true});
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [once]}, new Date(2026, 8, 13, 12))[0].daysUntil, 2);
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [once]}, new Date(2026, 8, 16, 12)).length, 0);
const monthly = occasions.normalizeOccasion({id: "card", name: "信用卡还款", kind: "scheduled", date: "2026-01-15", recurrence: "monthly", remindBeforeDays: 2, enabled: true});
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [monthly]}, new Date(2026, 8, 13, 12))[0].daysUntil, 2);
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [monthly]}, new Date(2026, 1, 27, 12)).length, 0);
const monthEnd = occasions.normalizeOccasion({id: "month-end", name: "月末扣费", kind: "scheduled", date: "2026-01-31", recurrence: "monthly", remindBeforeDays: 2, enabled: true});
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [monthEnd]}, new Date(2026, 1, 27, 12))[0].occurrenceDate, "2026-02-28");
const leapBirthday = occasions.normalizeOccasion({id:"leap", name:"闰年生日", kind:"birthday", date:"2028-02-29", recurrence:"annual", remindBeforeDays:3});
assert.equal(occasions.getVisibleOccasions({version:1, occasions:[leapBirthday]}, new Date(2027, 1, 27, 12)).length, 0);
assert.equal(occasions.getVisibleOccasions({version:1, occasions:[leapBirthday]}, new Date(2028, 1, 26, 12))[0].occurrenceDate, "2028-02-29");
const capped = occasions.normalizeOccasion({id:"capped", name:"限制", date:"2026-09-20", recurrence:"once", remindBeforeDays:999, completedDates:["2026-09-20","bad","2026-09-19"]});
assert.equal(capped.remindBeforeDays, 365); assert.deepEqual(capped.completedDates, ["2026-09-20","2026-09-19"]);
const unchanged = {version:1, occasions:[once]}; assert.equal(occasions.markOccasionCompleted(unchanged, "missing", "2026-09-15", true), unchanged);
const marked = occasions.markOccasionCompleted(unchanged, "loan", "2026-09-15", true); assert.notEqual(marked, unchanged); assert.equal(occasions.isOccasionCompleted(marked.occasions[0], "2026-09-15"), true); const unmarked = occasions.markOccasionCompleted(marked, "loan", "2026-09-15", false); assert.equal(occasions.isOccasionCompleted(unmarked.occasions[0], "2026-09-15"), false);
// v5 recurrence engine: lunar annual, weekly, quarterly, interval, month-end/nth-week variants.
const lunarBirthday = occasions.normalizeOccasion({id: "lunar-bday", name: "农历生日", kind: "birthday", date: "2026-02-17", recurrence: "annual", calendar: "lunar", remindBeforeDays: 3, enabled: true});
assert.ok(lunarBirthday, "lunar birthday normalizes");
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [lunarBirthday]}, new Date(2027, 1, 4, 12))[0].occurrenceDate, "2027-02-06",
    "lunar annual must land on 正月初一 2027 (2027-02-06)");
const weekly = occasions.normalizeOccasion({id: "weekly", name: "周会", kind: "scheduled", date: "2026-09-10", recurrence: "weekly", weekday: 4, remindBeforeDays: 1, enabled: true});
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [weekly]}, new Date(2026, 8, 10, 12))[0].status, "today");
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [weekly]}, new Date(2026, 8, 16, 12))[0].occurrenceDate, "2026-09-17");
const quarterly = occasions.normalizeOccasion({id: "q", name: "物业费", kind: "scheduled", date: "2026-03-10", recurrence: "quarterly", remindBeforeDays: 5, enabled: true});
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [quarterly]}, new Date(2026, 8, 8, 12))[0].occurrenceDate, "2026-09-10");
const interval = occasions.normalizeOccasion({id: "iv", name: "体检", kind: "scheduled", date: "2026-03-15", recurrence: "interval", intervalUnit: "month", intervalCount: 6, remindBeforeDays: 7, enabled: true});
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [interval]}, new Date(2026, 8, 12, 12))[0].occurrenceDate, "2026-09-15");
const nthWeek = occasions.normalizeOccasion({id: "moms-day", name: "母亲节", kind: "scheduled", date: "2026-05-10", recurrence: "annual", annualSubtype: "nthweek", month: 5, nthWeek: 2, weekday: 0, remindBeforeDays: 7, enabled: true});
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [nthWeek]}, new Date(2026, 4, 8, 12))[0].occurrenceDate, "2026-05-10",
    "mother's day 2026 is the 2nd sunday of may");
const lastDay = occasions.normalizeOccasion({id: "last", name: "月末", kind: "scheduled", date: "2026-01-31", recurrence: "monthly", monthlySubtype: "lastday", remindBeforeDays: 2, enabled: true});
assert.equal(occasions.getVisibleOccasions({version: 1, occasions: [lastDay]}, new Date(2026, 3, 28, 12))[0].occurrenceDate, "2026-04-30");
assert.ok(occasions.OCCASION_TEMPLATES.length >= 15, "occasion template library ships with the common fixtures");
console.log("Occasion model structure checks passed.");
