const assert = require("node:assert/strict");
const fs = require("node:fs");
const readme = fs.readFileSync("README.md", "utf8");
const source = fs.readFileSync("src/index.ts", "utf8");
const migration = fs.readFileSync("docs/v2.0-migration-notes.md", "utf8");
assert.match(readme, /界面密度/);
assert.match(readme, /跟随思源\/浅色\/深色/);
assert.match(readme, /减少动效/);
assert.match(readme, /显示偏好重置/);
assert.match(source, /data-action=\"reset-all-preferences\"/);
assert.match(source, /\[\"settings\", \"设置\",/);
assert.match(source, /data-setting-appearance/);
assert.match(source, /data-setting-motion/);
const resetMarkupIndex = source.indexOf('data-action=\"reset-all-preferences\"');
const resetBindingIndex = source.indexOf('root.querySelector<HTMLElement>("[data-action=\'reset-all-preferences\']")?.addEventListener');
assert(resetMarkupIndex >= 0 && resetBindingIndex > resetMarkupIndex);
assert.match(readme, /v2\.0-migration-notes\.md/);
assert.match(migration, /reducedMotion/);
assert.match(readme, /v2\.0-change-log\.md/);
assert.match(readme, /ui-redesign-roadmap\.md/);
console.log("Preferences documentation checks passed.");
