const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const ts = require("typescript");

const sourceRoot = path.join(__dirname, "..", "src");
const fragmentsSource = fs.readFileSync(path.join(sourceRoot, "render", "fragments.ts"), "utf8");
const todayBindSource = fs.readFileSync(path.join(sourceRoot, "render", "bind-today.ts"), "utf8");
const indexSource = fs.readFileSync(path.join(sourceRoot, "index.ts"), "utf8");
const stylesSource = fs.readFileSync(path.join(sourceRoot, "ui", "components.scss"), "utf8");
const i18nSource = fs.readFileSync(path.join(sourceRoot, "i18n.ts"), "utf8");
assert.match(fragmentsSource, /renderPriorityReminderView/);
assert.match(fragmentsSource, /selectPriorityReminders\(projectReminderCenter/);
assert.match(fragmentsSource, /data-priority-reminder/);
assert.match(fragmentsSource, /data-priority-source/);
assert.match(fragmentsSource, /data-priority-id/);
assert.match(fragmentsSource, /aria-live="polite"/);
assert.match(fragmentsSource, /priorityReminder/);
assert.match(todayBindSource, /data-priority-reminder/);
assert.match(todayBindSource, /showOccasions\(\)/);
assert.match(todayBindSource, /scrollIntoView/);
assert.match(todayBindSource, /CSS\.escape/);
assert.match(indexSource, /reminderUserActions: this\.reminderUserActions/);
assert.match(stylesSource, /\.lc-checkin__priority-reminder/);
assert.match(stylesSource, /\.lc-checkin__priority-reminder\.is-overdue/);
assert.match(i18nSource, /"today\.priorityTitle"/);
assert.match(i18nSource, /"today\.priorityActionAria"/);
const outputRoot = fs.mkdtempSync(path.join(os.tmpdir(), "siyuan-checkin-priority-reminder-"));
const source = fs.readFileSync(path.join(sourceRoot, "features", "priority-reminder.ts"), "utf8");
fs.mkdirSync(path.join(outputRoot, "features"), {recursive: true});
fs.writeFileSync(path.join(outputRoot, "features", "priority-reminder.js"), ts.transpileModule(source, {compilerOptions: {target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS}}).outputText, "utf8");
const priority = require(path.join(outputRoot, "features", "priority-reminder.js"));
const entry = (id, status, title, daysUntil = 0, source = "checkin") => ({id, source, sourceId: id, title, dueDate: "2026-09-14", daysUntil, status, note: ""});

const entries = [entry("upcoming", "upcoming", "未来", 2), entry("today-z", "today", "乙"), entry("overdue-b", "overdue", "逾期乙", -2), entry("overdue-a", "overdue", "逾期甲", -1), entry("done", "completed", "完成")];
const selected = priority.selectPriorityReminders(entries);
assert.deepEqual(selected.map((item) => item.id), ["overdue-b", "overdue-a", "today-z"]);
assert.deepEqual(entries.map((item) => item.id), ["upcoming", "today-z", "overdue-b", "overdue-a", "done"]);
const summary = priority.summarizePriorityReminders(entries);
assert.equal(summary.count, 3);
assert.equal(summary.first.id, "overdue-b");
assert.equal(priority.priorityReminderStatus(summary.first), "overdue");
assert.equal(priority.priorityReminderStatus(entry("none", "completed", "已完成")), "none");
assert.equal(priority.priorityReminderStatus(undefined), "none");

const tie = priority.selectPriorityReminders([entry("b", "today", "乙"), entry("a", "today", "甲")]);
assert.deepEqual(tie.map((item) => item.id), ["a", "b"]);
console.log("Priority reminder model checks passed: overdue/today filtering, stable ordering, summary and immutability.");
fs.rmSync(outputRoot, {recursive: true, force: true});
