const assert = require('node:assert/strict'); const fs = require('node:fs');
const source = fs.readFileSync('src/features/reminder-projection.ts','utf8');
assert.match(source,/reminderId/); assert.match(source,/sortReminders/); assert.match(source,/transitionReminder/); assert.match(source,/status === "completed"/);
assert.match(source,/projectOccasionReminder/); assert.match(source,/projectScheduleReminder/);
assert.match(source,/filterReminders/); assert.match(source,/options\.from/); assert.match(source,/options\.to/);
assert.match(source,/summarizeReminders/); assert.match(source,/pending: 0/);
assert.match(source,/normalizeReminderStatus/); assert.match(source,/item\.dueDate < today/);
assert.match(source,/prepareReminders/); assert.match(source,/items\.map/);
assert.match(source,/getReminderPriority/); assert.match(source,/count: pending\.length/);
assert.match(source,/reminderStatusLabel/); assert.match(source,/reminderPriorityText/);
assert.match(source,/reminderPriorityLabel/); assert.match(source,/status === "overdue"/);
assert.match(source,/mergeReminders/); assert.match(source,/byId = new Map/);
assert.match(source,/serializeReminders/); assert.match(source,/deserializeReminders/);
assert.match(source,/mergeReminders\(valid\)/); assert.match(source,/title\.length <= 200/);
console.log('Reminder projection structure checks passed.');
