const assert = require("node:assert/strict");
const fs = require("node:fs");
const source = fs.readFileSync("src/index.ts", "utf8");
assert.match(source, /type:\s*["']migration["']/);
assert.match(source, /buildRecoveryAuditDetails\("json-import", preflight, "rejected", validationErrors\)/);
assert.match(source, /type:\s*["']restore["']/);
assert.match(source, /buildRecoveryAuditDetails\("local-snapshot", preflight, "accepted"\)/);
assert.match(source, /readStoreSnapshotHistory\(raw\)/);
assert.match(source, /preflightJsonRecovery\(JSON\.stringify\(snapshot\.store\), normalizeStore, summarizeJsonBackup\(this\.store\)\)/);
assert.match(source, /appendStoreSnapshotHistory\(await this\.loadData\(BACKUP_STORAGE_NAME\), createStoreSnapshotEnvelope\(previous\)\)/);
assert.match(source, /snapshotCapturedAt: snapshot\.capturedAt, legacySnapshot: snapshot\.legacy/);
assert.match(source, /this\.store = backup;\s*try \{\s*await this\.persist\(\);/,
    "snapshot restore must persist the selected backup rather than the pre-restore store");
assert.doesNotMatch(source, /this\.store = backup;\s*try \{\s*await this\.persist\(current\);/);
assert.match(source, /buildRecoveryAuditDetails\("local-snapshot", preflight, "rejected", validationErrors\)/);
assert.match(source, /buildRecoveryAuditDetails\("json-import", preflight, "accepted"\)/);
assert.match(source, /assessment\.requiresReview/);
assert.match(source, /saveData\(AUDIT_STORAGE_NAME, this\.auditEntries\)/);
assert.match(source, /private async persistAuditBestEffort\(\): Promise<void>/);
assert.doesNotMatch(source, /void this\.saveData\(AUDIT_STORAGE_NAME/);
assert.ok((source.match(/appendStoreAudit\(this\.auditEntries/g) || []).length >= 4,
    "every audit write path must use the normalized append helper");
const exporter = fs.readFileSync("src/export.ts", "utf8");
assert.match(exporter, /status,\s*source,\s*sourceVersion:/);
assert.match(exporter, /errors\.length \? \{errors: \[\.\.\.errors\]\}/);
assert.match(source, /this\.store = previous/);
assert.match(source, /buildRecoveryAuditDetails\("json-import", preflight, "rejected", \["persist-failed"\]\)/);
assert.match(source, /buildRecoveryAuditDetails\("local-snapshot", preflight, "rejected", \["persist-failed"\]\)/);
assert.match(source, /Audit diagnostics must never interrupt or roll back/,
    "audit persistence failure must not roll back successfully restored data");
assert.match(source, /msg\.restoreFailed/);
const ops = fs.readFileSync("src/plugin-ops.ts", "utf8");
assert.match(ops, /downloadMigrationReportFor/);
assert.match(ops, /siyuan-checkin-migration-/);
assert.match(ops, /serializeJsonMigrationReport/);
assert.match(ops, /downloadStoreAuditFor/);
assert.match(ops, /siyuan-checkin-audit-/);
const settings = fs.readFileSync("src/render/settings.ts", "utf8");
assert.match(settings, /data-action="export-audit"/);
console.log("Restore and migration audit wiring checks passed.");
