const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const exists = (file) => fs.existsSync(path.join(root, file));
const pkg = JSON.parse(read("package.json"));
const plugin = JSON.parse(read("plugin.json"));
const ci = read(".github/workflows/ci.yml");
const smoke = read("docs/integration-smoke-checklist.md");
const rollback = read("docs/release-rollback.md");
const compatibility = read("docs/siyuan-compatibility.md");
const recovery = read("docs/v10-recovery-acceptance.md");
const roadmap = read("docs/archive/development-roadmap.md");
const environmentCheck = read("scripts/environment-check.cjs");

let passed = 0;
const check = (name, assertion) => {
    assertion();
    passed += 1;
    process.stdout.write(`ok ${passed} - ${name}\n`);
};

check("package and plugin versions agree", () => assert.equal(pkg.version, plugin.version));
check("release version is semantic", () => assert.match(pkg.version, /^\d+\.\d+\.\d+$/));
check("minimum SiYuan version is semantic", () => assert.match(plugin.minAppVersion, /^\d+\.\d+\.\d+$/));
check("plugin supports every backend", () => assert.deepEqual(plugin.backends, ["all"]));
check("desktop frontend is declared", () => assert(plugin.frontends.includes("desktop")));
check("desktop window frontend is declared", () => assert(plugin.frontends.includes("desktop-window")));
check("mobile frontend is declared", () => assert(plugin.frontends.includes("mobile")));
check("browser frontends are declared", () => assert(plugin.frontends.includes("browser-desktop") && plugin.frontends.includes("browser-mobile")));
check("publish mode remains enabled", () => assert.equal(plugin.disabledInPublish, false));
check("repository URL uses the project GitHub origin", () => assert.equal(plugin.url, "https://github.com/ai68298100/siyuan-checkin"));
check("plugin icon exists", () => assert(exists(plugin.icon)));
check("plugin preview exists", () => assert(exists(plugin.preview)));
check("localized readme target exists", () => assert(exists(plugin.readme["zh-CN"])));
check("license exists", () => assert(exists("LICENSE")));
check("pnpm lockfile exists", () => assert(exists("pnpm-lock.yaml")));
check("workspace build policy exists", () => assert(exists("pnpm-workspace.yaml")));
check("package manager is pinned", () => assert.match(pkg.packageManager, /^pnpm@\d+\.\d+\.\d+$/));
check("supported Node floor is declared", () => assert.match(pkg.engines.node, /^>=\d+/));
check("production build command is explicit", () => assert.match(pkg.scripts.build, /webpack.+--mode production/));
check("type check does not emit", () => assert.equal(pkg.scripts.check, "tsc --noEmit"));
check("release assets have a dedicated gate", () => assert.equal(pkg.scripts["check:release"], "node tests/release-assets.test.cjs"));
check("environment has a dedicated probe", () => assert.equal(pkg.scripts["check:environment"], "node scripts/environment-check.cjs"));
check("quality chain starts with environment probing", () => assert(pkg.scripts["test:quality"].startsWith("pnpm run check:environment")));
check("quality chain covers ecosystem contracts", () => assert.match(pkg.scripts["test:quality"], /pnpm run test:ecosystem/));
check("quality chain covers performance", () => assert.match(pkg.scripts["test:quality"], /pnpm run test:perf/));
check("quality chain covers release assets", () => assert.match(pkg.scripts["test:quality"], /pnpm run check:release/));
check("quality chain builds before checking release assets", () => {
    const quality = pkg.scripts["test:quality"];
    const buildIndex = quality.indexOf("pnpm run build");
    assert(buildIndex >= 0);
    assert(buildIndex < quality.indexOf("pnpm run check:release"));
});
check("quality chain builds before performance tests", () => {
    const quality = pkg.scripts["test:quality"];
    const buildIndex = quality.indexOf("pnpm run build");
    assert(buildIndex >= 0);
    assert(buildIndex < quality.indexOf("pnpm run test:perf"));
});
check("UI suite does not inspect stale release artifacts", () => {
    assert.doesNotMatch(pkg.scripts["test:ui"], /release-assets/);
});
check("CI verifies pushes to main", () => assert.match(ci, /push:\s*\n\s*branches: \[main\]/));
check("CI verifies pull requests", () => assert.match(ci, /pull_request:/));
check("CI pins Node 22", () => assert.equal((ci.match(/node-version: 22/g) || []).length, 2));
check("CI installs from the frozen lockfile", () => assert.equal((ci.match(/pnpm install --frozen-lockfile/g) || []).length, 2));
check("CI runs type checking", () => assert.match(ci, /run: pnpm run check\s/));
check("CI runs the production build", () => assert.equal((ci.match(/run: pnpm run build/g) || []).length, 2));
check("CI runs unit and structure tests", () => assert.match(ci, /run: pnpm test\s/));
check("CI runs mobile structure tests", () => assert.match(ci, /run: pnpm run test:mobile/));
check("CI runs release asset validation", () => assert.match(ci, /run: pnpm run check:release/));
check("CI installs Chromium for browser audits", () => assert.match(ci, /playwright install --with-deps chromium/));
check("CI runs accessibility audits", () => assert.match(ci, /node tests\/accessibility-audit\.test\.cjs/));
check("CI runs the visual walkthrough", () => assert.match(ci, /node tests\/visual-qa\.cjs/));
check("environment probe enumerates browser candidates", () => assert.match(environmentCheck, /browsers:\s*\[|for \(const browser of/));
check("environment probe reports machine-readable JSON", () => assert.match(environmentCheck, /JSON\.stringify/));
check("smoke matrix covers mobile, tab, and dock", () => assert.match(smoke, /手机全屏、桌面页签、dock 侧栏/));
check("smoke matrix covers two-window focus integration", () => assert.match(smoke, /## 番茄钟双窗口/));
check("smoke matrix covers reminder actions", () => assert.match(smoke, /延期 \/ 跳过/));
check("rollback guide requires a package hash", () => assert.match(rollback, /SHA-256/));
check("rollback guide forbids release version reuse", () => assert.match(rollback, /不重用已经公开的版本号或标签/));
check("compatibility guide includes desktop and mobile", () => assert.match(compatibility, /\| 思源版本 \| 桌面端 \| 移动端 \|/));
check("compatibility guide validates package contents", () => assert.match(compatibility, /package\.zip.*plugin\.json.*index\.js.*index\.css/));
check("recovery acceptance covers failure rollback", () => assert.match(recovery, /\| Failure rollback \|/));
check("recovery acceptance covers concurrent writes", () => assert.match(recovery, /\| Concurrent writes \|/));
check("9.8 roadmap orders field validation before later majors", () => assert.match(roadmap, /9\.8 现场验收 → 10\.0 恢复兼容维护/));

assert.equal(passed, 53, `expected 53 release-readiness checks, got ${passed}`);
console.log(`9.8 stability batch C checks passed (${passed} checks).`);
