const assert = require("node:assert/strict");
const fs = require("node:fs");
const render = fs.readFileSync("src/render/suggestion-workflow.ts", "utf8");
const styles = fs.readFileSync("src/ui/components.scss", "utf8");
const i18n = fs.readFileSync("src/i18n.ts", "utf8");
assert.match(render, /renderSuggestionWorkflowPanel/);
assert.match(render, /data-suggestion-workflow/);
assert.match(render, /data-suggestion-decision/);
assert.match(render, /data-suggestion-undo/);
assert.match(render, /workflowActions/);
assert.match(render, /workflowAuditSummary/);
assert.match(render, /agent\.workflowAuditMeta/);
assert.match(render, /agent\.confirmAria/);
assert.match(render, /agent\.cancelAria/);
assert.match(render, /agent\.undoAria/);
assert.match(render, /slice\(0, 8\)/);
assert.match(render, /hiddenCount/);
assert.match(render, /agent\.moreChanges/);
assert.match(render, /aria-live="polite"/);
assert.match(render, /workflowStatusAria/);
assert.match(render, /workflowActionsAria/);
assert.match(render, /latestWorkflowAudit/);
assert.match(render, /workflowUpdatedAt/);
assert.match(render, /lc-agent-suggestion-updated/);
assert.match(render, /escapeHtml\(String\(change\.field\)\)/);
assert.match(styles, /\.lc-checkin__suggestion-workflow/);
assert.match(styles, /\.lc-checkin__suggestion-workflow header/);
assert.match(styles, /\.lc-checkin__suggestion-workflow footer/);
assert.match(styles, /lc-agent-suggestion-more/);
assert.match(styles, /footer button\[disabled\]/);
assert.match(i18n, /"agent\.workflowAria"/);
assert.match(i18n, /"agent\.workflowAuditMeta"/);
assert.match(i18n, /"agent\.confirmedNotice"/);
assert.match(i18n, /"agent\.cancelledNotice"/);
assert.match(i18n, /"agent\.undoAccepted"/);
const review = fs.readFileSync("src/render/review.ts", "utf8");
const index = fs.readFileSync("src/index.ts", "utf8");
const integrations = fs.readFileSync("src/integrations.ts", "utf8");
const api = fs.readFileSync("src/api.ts", "utf8");
assert.match(review, /suggestionWorkflow\?:/);
assert.match(review, /renderSuggestionWorkflowPanel/);
assert.match(index, /normalizeSummaryProviderResult/);
assert.match(index, /createSuggestionWorkflow/);
assert.match(index, /normalized\.suggestions\[0\]/);
assert.match(integrations, /string \| \{text: string; suggestions\?: AgentSuggestion\[\]\}/);
assert.match(api, /normalizeSummaryProviderResult/);
console.log("Suggestion workflow render structure checks passed.");
