const assert = require("node:assert/strict");
const fs = require("node:fs");
const render = fs.readFileSync("src/render/suggestion-workflow.ts", "utf8");
const styles = fs.readFileSync("src/ui/components.scss", "utf8");
const i18n = fs.readFileSync("src/i18n.ts", "utf8");
assert.match(render, /renderSuggestionWorkflowPanel/);
assert.match(render, /data-suggestion-workflow/);
assert.match(render, /data-suggestion-decision/);
assert.match(render, /data-suggestion-undo/);
assert.match(render, /canUndoSuggestion/);
assert.match(render, /workflowAuditSummary/);
assert.match(render, /agent\.workflowAuditMeta/);
assert.match(render, /agent\.confirmAria/);
assert.match(render, /agent\.cancelAria/);
assert.match(render, /agent\.undoAria/);
assert.match(render, /slice\(0, 8\)/);
assert.match(render, /escapeHtml\(String\(change\.field\)\)/);
assert.match(styles, /\.lc-checkin__suggestion-workflow/);
assert.match(styles, /\.lc-checkin__suggestion-workflow header/);
assert.match(styles, /\.lc-checkin__suggestion-workflow footer/);
assert.match(i18n, /"agent\.workflowAria"/);
assert.match(i18n, /"agent\.workflowAuditMeta"/);
console.log("Suggestion workflow render structure checks passed.");
