const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const ts = require("typescript");

const root = fs.mkdtempSync(path.join(os.tmpdir(), "siyuan-checkin-suggestion-"));
fs.writeFileSync(path.join(root, "i18n.js"), "exports.t=(key, vars={})=>key.replace(/\\{(\\w+)\\}/g, (_, name)=>String(vars[name] ?? ''));", "utf8");
const source = fs.readFileSync(path.join(__dirname, "..", "src", "agent-suggestions.ts"), "utf8");
fs.writeFileSync(path.join(root, "agent-suggestions.js"), ts.transpileModule(source, {compilerOptions: {target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS}}).outputText, "utf8");
const model = require(path.join(root, "agent-suggestions.js"));
const item = {id: "a", name: "阅读", target: 1, unit: "次", kind: "count", priority: "medium", timeSlot: "any", tomatoMode: "off", createdAt: "2026-01-01", updatedAt: "2026-01-01", archived: false, archivePeriods: [], schedule: {type: "daily"}};
const store = {version: 1, items: [item], events: [], eventTombstones: []};
const suggestion = {id: "s1", title: "调整", reason: "", changes: [{itemId: "a", field: "target", before: 1, after: 2}], requiresConfirmation: true};
const pending = model.createSuggestionEnvelope(suggestion, "2026-09-14T00:00:00.000Z");
assert.equal(model.canConfirmSuggestion(pending), true);
assert.equal(model.normalizeSummaryProviderResult("摘要", [item]).text, "摘要");
assert.equal(model.normalizeSummaryProviderResult({text: "摘要", suggestions: [suggestion]}, [item]).suggestions.length, 1);
assert.equal(model.normalizeSummaryProviderResult({text: "", suggestions: [{...suggestion, changes: []}]}, [item]).suggestions.length, 0);
assert.equal(model.normalizeSummaryProviderResult({text: "x".repeat(200001)}, [item]), undefined);
const decisionToken = model.createSuggestionDecisionToken(pending, "confirm", "2026-09-14T00:02:00.000Z", "nonce-1");
assert.equal(model.isSuggestionDecisionValid(pending, decisionToken, new Date("2026-09-14T00:05:00.000Z")), true);
assert.equal(model.parseSuggestionDecisionToken(decisionToken).decision, "confirm");
assert.equal(model.isSuggestionDecisionValid(pending, decisionToken, new Date("2026-09-14T00:13:00.000Z")), false);
assert.equal(model.isSuggestionDecisionValid(pending, decisionToken.replace("s1|s1", "s1|other"), new Date("2026-09-14T00:05:00.000Z")), false);
assert.equal(model.parseSuggestionDecisionToken("broken"), undefined);
assert.equal(model.createSuggestionDecisionToken(pending, "confirm", "bad", "n"), "");
const consumedOnce = model.consumeSuggestionDecision([], pending, decisionToken, "confirm", new Date("2026-09-14T00:05:00.000Z"));
assert.equal(consumedOnce.accepted, true);
const replayed = model.consumeSuggestionDecision(consumedOnce.consumed, pending, decisionToken, "confirm", new Date("2026-09-14T00:05:00.000Z"));
assert.equal(replayed.reason, "replayed");
assert.equal(model.consumeSuggestionDecision([], pending, decisionToken, "cancel", new Date("2026-09-14T00:05:00.000Z")).reason, "wrong-decision");
assert.equal(model.confirmSuggestionWithToken(pending, decisionToken, new Date("2026-09-14T00:05:00.000Z")).status, "confirmed");
const cancelToken = model.createSuggestionDecisionToken(pending, "cancel", "2026-09-14T00:02:00.000Z", "nonce-2");
assert.equal(model.cancelSuggestionWithToken(pending, cancelToken, new Date("2026-09-14T00:05:00.000Z")).status, "cancelled");
assert.equal(model.confirmSuggestionWithToken(pending, cancelToken, new Date("2026-09-14T00:05:00.000Z")), undefined);
const normalized = model.normalizeSuggestionEnvelope({...pending, title: "调整", reason: "建议"}, [item]);
assert.equal(normalized.changes.length, 1);
assert.equal(model.normalizeSuggestionEnvelope({...pending, requiresConfirmation: false}, [item]), undefined);
assert.equal(model.normalizeSuggestionEnvelope({...pending, createdAt: "invalid"}, [item]), undefined);
const serialized = model.serializeSuggestionEnvelope(pending);
assert.equal(model.deserializeSuggestionEnvelope(serialized, [item]).id, "s1");
assert.equal(model.deserializeSuggestionEnvelope("{bad", [item]), undefined);
assert.equal(model.applyConfirmedSuggestion(store, pending).applied, 0);
const confirmed = model.transitionSuggestionStatus(pending, "confirmed", "2026-09-14T00:01:00.000Z");
const applied = model.applyConfirmedSuggestion(store, confirmed);
assert.equal(applied.applied, 1);
assert.equal(applied.store.items[0].target, 2);
const applyAudit = model.suggestionApplyAudit(confirmed, applied, "2026-09-14T00:06:00.000Z");
assert.equal(applyAudit.action, "applied");
assert.equal(applyAudit.applied, 1);
const reverted = model.revertSuggestionApplication(applied.store, confirmed);
assert.equal(reverted.reverted, 1);
assert.equal(reverted.store.items[0].target, 1);
const changedAfterApply = {...applied.store, items: [{...applied.store.items[0], target: 3}]};
const revertConflict = model.revertSuggestionApplication(changedAfterApply, confirmed);
assert.equal(revertConflict.reverted, 0);
assert.deepEqual(revertConflict.conflicts, ["a:target"]);
assert.equal(revertConflict.store.items[0].target, 3);
const revertAudit = model.suggestionRevertAudit(confirmed, reverted, "2026-09-14T00:07:00.000Z");
assert.equal(revertAudit.reason, "revert");
assert.equal(model.suggestionDecisionAudit(confirmed, "confirm").action, "confirmed");
assert.equal(model.suggestionDecisionAudit(confirmed, "cancel").action, "cancelled");
const stale = {...confirmed, changes: [{...confirmed.changes[0], before: 99}]};
const conflict = model.applyConfirmedSuggestion(store, stale);
assert.equal(conflict.applied, 0);
assert.deepEqual(conflict.conflicts, ["a:target"]);
assert.equal(conflict.store, store);
const audits = Array.from({length: 55}, (_, index) => ({suggestionId: `s-${index}`, action: index % 2 ? "created" : "confirmed", at: "2026-09-14T00:00:00.000Z"}));
const normalizedAudits = model.normalizeSuggestionAudits(audits);
assert.equal(normalizedAudits.length, 50);
assert.equal(normalizedAudits[0].suggestionId, "s-5");
assert.deepEqual(model.summarizeSuggestionAudits(normalizedAudits), {created: 25, confirmed: 25, cancelled: 0, applied: 0, rejected: 0});
const auditJson = model.serializeSuggestionAudits(normalizedAudits);
assert.equal(model.deserializeSuggestionAudits(auditJson).length, 50);
assert.deepEqual(model.deserializeSuggestionAudits('{"version":99,"audits":[]}'), []);
assert.deepEqual(model.deserializeSuggestionAudits("broken"), []);
assert.equal(model.appendSuggestionAudit(normalizedAudits, {suggestionId: "s-new", action: "applied", at: "2026-09-14T00:00:00.000Z", applied: 1}).length, 50);
assert.equal(model.normalizeSuggestionAudits([{suggestionId: "x", action: "oops", at: "2026-09-14T00:00:00.000Z"}]).length, 0);
assert.equal(model.normalizeSuggestionAudits([{suggestionId: "x", action: "created", at: "bad"}]).length, 0);
assert.equal(model.normalizeSuggestionAudits([{suggestionId: "x", action: "created", at: "2026-09-14T00:00:00.000Z", applied: -1}]).length, 0);
const dangerous = {...confirmed, changes: [{itemId: "a", field: "__proto__", before: undefined, after: {polluted: true}}]};
assert.equal(model.applyConfirmedSuggestion(store, dangerous).applied, 0);
fs.rmSync(root, {recursive: true, force: true});
console.log("Suggestion confirmation and conflict guards passed.");
