const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const source = fs.readFileSync(path.join(root, "src", "render", "today-bindings.ts"), "utf8");
const index = fs.readFileSync(path.join(root, "src", "index.ts"), "utf8");
const styles = fs.readFileSync(path.join(root, "src", "ui", "components.scss"), "utf8");

assert.match(source, /export function bindItemContextMenuFor\(/, "Today cards expose a context-menu binding");
assert.match(source, /event\.pointerType !== "touch" && event\.pointerType !== "pen"/, "touch and pen pointers are eligible for long press");
assert.match(source, /window\.setTimeout\(\(\) => \{[\s\S]*?520\)/, "long press waits long enough to avoid accidental activation");
assert.match(source, /Math\.hypot\(event\.clientX - longPressStartX, event\.clientY - longPressStartY\) > 10/, "pointer movement cancels a long press");
assert.match(source, /suppressContextMenuUntil = Date\.now\(\) \+ 800/, "native follow-up contextmenu is suppressed after long press");
assert.match(source, /Math\.min\(Math\.max\(margin, clientX\), maxX\)/, "menu is clamped to the horizontal viewport");
assert.match(source, /Math\.min\(Math\.max\(margin, clientY\), maxY\)/, "menu is clamped to the vertical viewport");
assert.match(source, /menu\.querySelector<HTMLElement>\("\[data-menu-action\]"\)\?\.focus\(\)/, "opening the menu moves focus to its first action");
assert.match(source, /event\.key === "Escape"[\s\S]*?closeMenus\(true\)/, "Escape closes an open menu");
assert.match(source, /closeMenus\(true\)/, "closing the menu restores focus to the card action");
assert.match(source, /menu\.setAttribute\("role", "menu"\)/, "context menu exposes menu semantics");
assert.match(source, /role="menuitem"/, "context menu actions expose menuitem semantics");
assert.match(source, /\["ArrowDown", "ArrowUp"\]/, "context menu supports keyboard traversal");
assert.match(source, /event\.key === "Home" \|\| event\.key === "End"/, "context menu supports first/last keyboard navigation");
assert.match(source, /event\.key === "Tab"[\s\S]*?closeMenus\(true\)/, "Tab closes the menu and restores a stable focus target");
assert.match(source, /menu\.setAttribute\("aria-busy", "true"\)/, "context menu exposes its pending state");
assert.match(source, /querySelectorAll<HTMLButtonElement>\("\[data-menu-action\]"\)[\s\S]*?button\.disabled = true/, "one menu mutation disables every competing action");
assert.match(source, /function runExclusiveAction\(/, "bulk actions share an exclusive execution guard");
assert.match(source, /button\.closest<HTMLElement>\("\[data-bulk-toolbar\]"\)/, "bulk action guard coordinates the whole toolbar");
assert.match(source, /Promise\.resolve\(\)\.then\(operation\)/, "synchronous action failures also release the busy guard");
assert.match(source, /button\.dataset\.actionBusy === "true"/, "repeated action clicks are ignored while a mutation is pending");
assert.match(source, /button\.setAttribute\("aria-busy", "true"\)/, "pending actions expose busy state");
assert.match(source, /await host\.archiveItems\(ids\)/, "bulk archive delegates to one host transaction");
assert.match(source, /await host\.deleteItemsWithRecords\(ids\)/, "bulk delete delegates to one host transaction");
assert.match(index, /private async archiveItems[\s\S]*?return this\.enqueueMutation[\s\S]*?await this\.persist\(\)/, "bulk archive persists once inside the mutation queue");
assert.match(index, /private async deleteItemsWithRecords[\s\S]*?deleteItemsCascade[\s\S]*?await this\.persist\(\)/, "bulk deletion uses the linear cascade and persists once");
assert.match(index, /private async recordEvent[\s\S]*?this\.maybeAutoArchiveAfterRecord\(current\)/, "manual records participate in automatic archiving");
assert.match(source, /menu\.dataset\.actionBusy === "true"/, "context-menu actions ignore duplicate clicks");
assert.match(fs.readFileSync(path.join(root, "src", "render", "fragments.ts"), "utf8"), /data-bulk-toolbar/, "bulk toolbar exposes a coordination boundary");
assert.match(styles, /\.lc-checkin__item-context-menu \{[\s\S]*?position: fixed;/, "context menu is positioned against the viewport");

console.log("Today context-menu checks passed.");
