const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const styles = fs.readFileSync(path.join(__dirname, "..", "src", "index.scss"), "utf8");
const source = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
assert.match(styles, /--lc-checkin-control-height:\s*36px/);
assert.match(styles, /--lc-checkin-muted-surface:/);
assert.match(styles, /--lc-checkin-shadow:/);
assert.match(styles, /\.lc-checkin__organize[\s\S]*background:\s*var\(--lc-checkin-muted-surface\)/);
assert.match(styles, /\.lc-checkin__item[\s\S]*box-shadow:\s*var\(--lc-checkin-shadow\)/);
assert.match(styles, /@container\s+lc-checkin\s+\(min-width:\s*720px\)[\s\S]*\.lc-checkin__form-scroll[\s\S]*grid-template-columns/);
assert.match(styles, /@container\s+lc-checkin\s+\(max-width:\s*440px\)[\s\S]*\.lc-checkin__item-name[\s\S]*overflow-wrap:\s*anywhere/);
assert.match(styles, /@container\s+lc-checkin\s+\(max-width:\s*340px\)/);
assert.match(styles, /backdrop-filter:\s*blur\(12px\)/);
assert.match(styles, /\.lc-checkin__summary-stats[\s\S]*grid-template-columns:\s*repeat\(3/);
assert.match(styles, /\.lc-checkin--history \.lc-checkin__history-event \.lc-checkin__text-button[\s\S]*min-width:\s*36px/);
assert.match(source, /lc-checkin--review[\s\S]*lc-checkin__summary-stats/);
assert.match(source, /lc-checkin--archived[\s\S]*暂不参与今日计划/);
assert.ok(source.includes('t("review.eyebrow")'), "review eyebrow uses the i18n dictionary");
assert.match(source, /surface\.dataset\.appearance = this\.resolvedAppearance\(\)/);
assert.match(source, /surface\.dataset\.appearance = this\.resolvedAppearance\(\)/);
assert.match(source, /surface\.dataset\.reducedMotion = String\(this\.reducedMotion\)/);
assert.match(source, /lc-checkin__settings-nav/);
assert.match(source, /确定恢复全部显示偏好吗/);
assert.match(styles, /\.lc-checkin\[data-reduced-motion="true"\]/);
assert.match(styles, /--lc-checkin-success:[^;]*#63c98d/);
assert.match(styles, /--lc-checkin-danger:[^;]*#b83232/);
assert.match(styles, /--lc-checkin-radius-lg:\s*16px/, "v5 tokens define the large radius");
assert.ok(!source.includes("cycleDensity"), "density cycler must be removed");
console.log("Modern responsive UI theme checks passed.");
